In [1]:
import pandas as pd
import numpy as np

import tabula

In [2]:
import sys
print(sys.executable)

/home/facrchad/venvs/tabula_env/bin/python

$$
$$\text{20 points} =
\begin{cases}
\begin{aligned}
\text{French} &= 2:
  \begin{aligned}[t]
  &0.5~\text{midterm} \\
  &0.75~\text{oral} \\
  &0.75~\text{final}
  \end{aligned} \\
\\[-4pt]
\text{Math} &= 4:
  \begin{aligned}[t]
  &0.67~\text{notebooks} \\
  &1.33~\text{midterm} \\
  &2~\text{final}
  \end{aligned} \\
\\[-4pt]
\text{Physics} &= 4:
  \begin{aligned}[t]
  &1.6~\text{point mechanics} \\
  &1.6~\text{thermodynamics} \\
  &0.8~\text{fluid mechanics}
  \end{aligned} \\
\\[-4pt]
\text{Chemistry} &= 2.67:
  \begin{aligned}[t]
  &\text{Chem Lab} = 1.33:
    \begin{aligned}[t]
    &0.66~\text{evaluated practical work} \\
    &0.33~\text{report} \\
    &0.33~\text{lab behaviour}
    \end{aligned} \\
  &\text{AOM} = 1.33:
    \begin{aligned}[t]
    &0.44~\text{midterm} \\
    &0.88~\text{final}
    \end{aligned}
  \end{aligned} \\
\\[-4pt]
\text{CS} &= 7.33:
  \begin{aligned}[t]
  &\text{CSPC} = 1.83:
    \begin{aligned}[t]
    &0.37~\text{midterm} \\
    &0.73~\text{final} \\
    &0.73~\text{PW}
    \end{aligned} \\
  &\text{Front-end} = 1.83:
    \begin{aligned}[t]
    &0.18~\text{PW} \\
    &0.73~\text{project} \\
    &0.92~\text{final}
    \end{aligned} \\
  &\text{DSA} = 3.67:
    \begin{aligned}[t]
    &1.83~\text{PW and project} \\
    &1.83~\text{exam}
    \end{aligned}
  \end{aligned}
\end{aligned}
\end{cases}$$
$$

- [x] French Midterm
- [x] French Oral
- [x] French Final
---
- [x] Math Midterm
- [x] Math Participation
- [ ] Math Final
---
- [x] Point Mechanihcs
- [x] Thermodynamics
- [x] Fluid Mechanics
---
- [ ] Chem Labs
- [x] AOM mid
- [x] AOM final
---
- [x] CSPC midterm
- [x] CSPC PW
- [x] CSPC Final
---
- [x] FrontEnd
- [x] DSA

## French Midterm

In [3]:
df_french_cc1 = pd.read_excel("grades/L1 French grades CC1-CC2-CC3_S1_2025.xlsx", sheet_name="CS")

In [4]:
df_french_cc1

   Unnamed: 0 Academic Year 2025/2026 Unnamed: 2 Unnamed: 3 Unnamed: 4
0         NaN                     NaN        NaN        NaN        NaN
1         NaN     Computer science L1        NaN        NaN        NaN
2         NaN                     NaN        NaN        NaN        NaN
3         NaN              Semester 1     French        NaN        NaN
4         NaN                     NaN        NaN        NaN        NaN
..        ...                     ...        ...        ...        ...
65         27                22423199         18         17         18
66         28                22423337       10,5       12.5         16
67         29                22423230         16       19.5         20
68         30                22423304       18,5         18         17
69         31                22423244       18,5       16.5         20

[70 rows x 5 columns]

In [5]:
df_french_cc1.drop([0, 1, 2, 3, 4, 5, 6],inplace=True)
df_french_cc1

   Unnamed: 0 Academic Year 2025/2026 Unnamed: 2 Unnamed: 3 Unnamed: 4
7           1                22423021         17       17,5       18.5
8           2                22423178         13         15       15.5
9           3                22423324         17      17,75         15
10          4                22422983         19         14       11.5
11          5                22423198         15         16       13.5
..        ...                     ...        ...        ...        ...
65         27                22423199         18         17         18
66         28                22423337       10,5       12.5         16
67         29                22423230         16       19.5         20
68         30                22423304       18,5         18         17
69         31                22423244       18,5       16.5         20

[63 rows x 5 columns]

In [6]:
df = df_french_cc1[["Academic Year 2025/2026", "Unnamed: 2"]]
df.rename(columns={'Academic Year 2025/2026' : 'ID', 'Unnamed: 2' : 'French Midterm 1'}, inplace=True)
df

/tmp/ipykernel_13964/2195735673.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={'Academic Year 2025/2026' : 'ID', 'Unnamed: 2' : 'French Midterm 1'}, inplace=True)

          ID French Midterm 1
7   22423021               17
8   22423178               13
9   22423324               17
10  22422983               19
11  22423198               15
..       ...              ...
65  22423199               18
66  22423337             10,5
67  22423230               16
68  22423304             18,5
69  22423244             18,5

[63 rows x 2 columns]

### Names

In [7]:
df_names = pd.read_excel("grades/L1-024_Subgroups.xlsx", sheet_name="CS-024 EX")
df_names

                  Academic Year 2025/2026  Unnamed: 1           Unnamed: 2
0                                     NaN         NaN                  NaN
1   L1 Option: Computer Science  CS-024;          NaN                  NaN
2                                   S.No.  Student ID                Email
3                            Exercise CS1         NaN                  NaN
4                                       1    22423021    f.abbasli@ufaz.az
..                                    ...         ...                  ...
63                                     27    22423199  m.taghiyeva@ufaz.az
64                                     28    22423337    z.valiyev@ufaz.az
65                                     29    22423230  n.yusibzada@ufaz.az
66                                     30    22423304    t.yusubov@ufaz.az
67                                     31    22423244   n.zahidova@ufaz.az

[68 rows x 3 columns]

In [8]:
df_names.drop([0, 1, 2, 3], inplace=True)
df_names.drop(["Academic Year 2025/2026"], axis=1, inplace=True)

df_names

   Unnamed: 1              Unnamed: 2
4    22423021       f.abbasli@ufaz.az
5    22423178       i.abbasli@ufaz.az
6    22423324     t.abbaszada@ufaz.az
7    22422983  a.abdurahmanov@ufaz.az
8    22423198       m.abishov@ufaz.az
..        ...                     ...
63   22423199     m.taghiyeva@ufaz.az
64   22423337       z.valiyev@ufaz.az
65   22423230     n.yusibzada@ufaz.az
66   22423304       t.yusubov@ufaz.az
67   22423244      n.zahidova@ufaz.az

[64 rows x 2 columns]

In [9]:
df_names.dropna()
df_names.rename(columns={"Unnamed: 1" : "ID", "Unnamed: 2" : "Email"}, inplace=True)
df_names

          ID                   Email
4   22423021       f.abbasli@ufaz.az
5   22423178       i.abbasli@ufaz.az
6   22423324     t.abbaszada@ufaz.az
7   22422983  a.abdurahmanov@ufaz.az
8   22423198       m.abishov@ufaz.az
..       ...                     ...
63  22423199     m.taghiyeva@ufaz.az
64  22423337       z.valiyev@ufaz.az
65  22423230     n.yusibzada@ufaz.az
66  22423304       t.yusubov@ufaz.az
67  22423244      n.zahidova@ufaz.az

[64 rows x 2 columns]

In [10]:

df

          ID French Midterm 1
7   22423021               17
8   22423178               13
9   22423324               17
10  22422983               19
11  22423198               15
..       ...              ...
65  22423199               18
66  22423337             10,5
67  22423230               16
68  22423304             18,5
69  22423244             18,5

[63 rows x 2 columns]

## French Final

In [11]:
df['French Final'] = df_french_cc1[["Unnamed: 4"]]

/tmp/ipykernel_13964/1065068656.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['French Final'] = df_french_cc1[["Unnamed: 4"]]

In [12]:
df

          ID French Midterm 1 French Final
7   22423021               17         18.5
8   22423178               13         15.5
9   22423324               17           15
10  22422983               19         11.5
11  22423198               15         13.5
..       ...              ...          ...
65  22423199               18           18
66  22423337             10,5           16
67  22423230               16           20
68  22423304             18,5           17
69  22423244             18,5           20

[63 rows x 3 columns]

## French Oral

In [13]:
df['French Oral'] = df_french_cc1[['Unnamed: 3']]
df

/tmp/ipykernel_13964/3543222334.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['French Oral'] = df_french_cc1[['Unnamed: 3']]

          ID French Midterm 1 French Final French Oral
7   22423021               17         18.5        17,5
8   22423178               13         15.5          15
9   22423324               17           15       17,75
10  22422983               19         11.5          14
11  22423198               15         13.5          16
..       ...              ...          ...         ...
65  22423199               18           18          17
66  22423337             10,5           16        12.5
67  22423230               16           20        19.5
68  22423304             18,5           17          18
69  22423244             18,5           20        16.5

[63 rows x 4 columns]

## CSPC Midterm

In [14]:
#df_cspc_mid =  pd.read_excel("grades/L1-024 CSPC Grade sheet.xlsx", sheet_name="CS")

In [15]:
#df_cspc_mid

In [16]:
#df_cspc_mid.drop([0, 1, 2, 3, 4, 5, 6],inplace=True)
#df["CSPC midterm"] = df_cspc_mid["Unnamed: 2"]
#df

## CSPC final and PWs

In [17]:
cspc = pd.read_excel("grades/L1 CSPC grades after review.xlsx", sheet_name="CS")
cspc

   Unnamed: 0               Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0         NaN  Academic Year 2025/2026        NaN        NaN        NaN
1         NaN                      NaN        NaN        NaN        NaN
2         NaN                      NaN        NaN        NaN        NaN
3         NaN               Semester 1       CSPC        NaN        NaN
4         NaN                      NaN        NaN        NaN        NaN
..        ...                      ...        ...        ...        ...
69        NaN                      NaN        NaN        NaN        NaN
70        NaN                      NaN        NaN        NaN        NaN
71        NaN                      NaN        NaN        NaN        NaN
72        NaN                      NaN        NaN        NaN        NaN
73          2                 22423229        NaN        NaN        NaN

[74 rows x 5 columns]

In [18]:
cspc.drop([0, 1, 2, 3, 4, 5, 6],inplace=True)
cspc

   Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
7           1   22423021     18.667    10.8355  15.769231
8           2   22423178     14.001     12.835  18.076923
9           3   22423324     18.667    12.1685  19.230769
10          4   22422983     12.002      7.002  15.897436
11          5   22423198     12.335     7.8345  15.769231
..        ...        ...        ...        ...        ...
69        NaN        NaN        NaN        NaN        NaN
70        NaN        NaN        NaN        NaN        NaN
71        NaN        NaN        NaN        NaN        NaN
72        NaN        NaN        NaN        NaN        NaN
73          2   22423229        NaN        NaN        NaN

[67 rows x 5 columns]

In [19]:
cspc.drop(['Unnamed: 0'], axis=1, inplace=True)
cspc

   Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
7    22423021     18.667    10.8355  15.769231
8    22423178     14.001     12.835  18.076923
9    22423324     18.667    12.1685  19.230769
10   22422983     12.002      7.002  15.897436
11   22423198     12.335     7.8345  15.769231
..        ...        ...        ...        ...
69        NaN        NaN        NaN        NaN
70        NaN        NaN        NaN        NaN
71        NaN        NaN        NaN        NaN
72        NaN        NaN        NaN        NaN
73   22423229        NaN        NaN        NaN

[67 rows x 4 columns]

In [20]:
cspc.rename(columns={'Unnamed: 1' : 'ID',
                     'Unnamed: 2' : 'CSPC midterm',
                     'Unnamed: 3' : 'CSPC Final',
                     'Unnamed: 4' : 'CSPC PW'},
            inplace=True)
cspc

          ID CSPC midterm CSPC Final    CSPC PW
7   22423021       18.667    10.8355  15.769231
8   22423178       14.001     12.835  18.076923
9   22423324       18.667    12.1685  19.230769
10  22422983       12.002      7.002  15.897436
11  22423198       12.335     7.8345  15.769231
..       ...          ...        ...        ...
69       NaN          NaN        NaN        NaN
70       NaN          NaN        NaN        NaN
71       NaN          NaN        NaN        NaN
72       NaN          NaN        NaN        NaN
73  22423229          NaN        NaN        NaN

[67 rows x 4 columns]

In [21]:
df = pd.merge(df, cspc, on='ID')

In [22]:
df

,ID,French Midterm 1,French Final,French Oral,CSPC midterm,CSPC Final,CSPC PW
0,22423021,17,18.5,"17,5",18.667,10.8355,15.769231
1,22423178,13,15.5,15,14.001,12.835,18.076923
2,22423324,17,15,"17,75",18.667,12.1685,19.230769
3,22422983,19,11.5,14,12.002,7.002,15.897436
4,22423198,15,13.5,16,12.335,7.8345,15.769231
...,...,...,...,...,...,...,...
61,22423199,18,18,17,14.668,12.6685,11.645833
62,22423337,"10,5",16,12.5,14.668,14.0015,11.270833
63,22423230,16,20,19.5,16.334,10.002,8.75
64,22423304,"18,5",17,18,14.668,13.168,13.020833
65,22423244,"18,5",20,16.5,14.668,11.1685,10.729167

## DSA Midterm

In [23]:
#df_dsa = pd.read_excel("grades/L1 CS 024 Grade sheet-Exam-DSA1-2025 sts.xlsx", sheet_name="CS")
#df_dsa

In [24]:
#df_dsa.drop([0, 1, 2, 3, 4, 5],inplace=True)
#df_dsa.drop(["Unnamed: 0", "Unnamed: 3", "Unnamed: 4"], axis=1, inplace=True)
#df_dsa.rename(columns={'Academic Year 2025/2026' : 'ID', 'Unnamed: 2' : 'DSA midterm'}, inplace=True)
#df_dsa

In [25]:
#df = pd.merge(df, df_dsa, on="ID")

## DSA Total

In [26]:
df_dsa = pd.read_excel('grades/L1-024 Grades Final DSA1.xlsx')
df_dsa

   Unnamed: 0 Academic Year 2025/2026 Unnamed: 2 Unnamed: 3 Unnamed: 4
0         NaN                     NaN        NaN        NaN        NaN
1         NaN     Computer science L1        NaN        NaN        NaN
2         NaN                     NaN        NaN        NaN        NaN
3         NaN              Semester 1        NaN        NaN        NaN
4         NaN                     NaN        NaN        NaN        NaN
..        ...                     ...        ...        ...        ...
65         27                22423199      14.75  14.833335       14.8
66         28                22423337          9  15.583335       12.3
67         29                22423230         12  16.583335       14.3
68         30                22423304          8       17.5       12.8
69         31                22423244        7.5     15.625       11.6

[70 rows x 5 columns]

In [27]:
df_dsa.drop([0, 1, 2, 3, 4, 5, 6],inplace=True)
df_dsa.drop(["Unnamed: 0", "Unnamed: 2", "Unnamed: 3"], axis=1, inplace=True)
df_dsa.rename(columns={'Academic Year 2025/2026' : 'ID', 'Unnamed: 4' : 'DSA total'}, inplace=True)
df_dsa

          ID DSA total
7   22423021        12
8   22423178      16.1
9   22423324      15.5
10  22422983      16.2
11  22423198      12.3
..       ...       ...
65  22423199      14.8
66  22423337      12.3
67  22423230      14.3
68  22423304      12.8
69  22423244      11.6

[63 rows x 2 columns]

In [28]:
#df_dsa['ID'] = df_dsa['ID'].astype(str).str.strip()
#df['ID'] = df['ID'].astype(str).str.strip()

df = pd.merge(df, df_dsa, on='ID')
df

,ID,French Midterm 1,French Final,French Oral,CSPC midterm,CSPC Final,CSPC PW,DSA total
0,22423021,17,18.5,"17,5",18.667,10.8355,15.769231,12
1,22423178,13,15.5,15,14.001,12.835,18.076923,16.1
2,22423324,17,15,"17,75",18.667,12.1685,19.230769,15.5
3,22422983,19,11.5,14,12.002,7.002,15.897436,16.2
4,22423198,15,13.5,16,12.335,7.8345,15.769231,12.3
...,...,...,...,...,...,...,...,...
61,22423199,18,18,17,14.668,12.6685,11.645833,14.8
62,22423337,"10,5",16,12.5,14.668,14.0015,11.270833,12.3
63,22423230,16,20,19.5,16.334,10.002,8.75,14.3
64,22423304,"18,5",17,18,14.668,13.168,13.020833,12.8
65,22423244,"18,5",20,16.5,14.668,11.1685,10.729167,11.6

## Math Midterm

In [29]:
df_math_mid = pd.read_excel("grades/L1 math Midterm Grade Sheet.xlsx", sheet_name="CS")
df_math_mid

   Unnamed: 0 Academic Year 2025/2026 Unnamed: 2 Unnamed: 3 Unnamed: 4
0         NaN                     NaN        NaN        NaN        NaN
1         NaN     Computer science L1        NaN        NaN        NaN
2         NaN                     NaN        NaN        NaN        NaN
3         NaN              Semester 1        NaN        NaN        NaN
4         NaN                     NaN        NaN        NaN        NaN
..        ...                     ...        ...        ...        ...
65         27                22423199        NaN      16,25        NaN
66         28                22423337        NaN       8,75        NaN
67         29                22423230        NaN      12,50        NaN
68         30                22423304        NaN      11,75        NaN
69         31                22423244        NaN       7,00        NaN

[70 rows x 5 columns]

In [30]:
df_math_mid.drop([0, 1, 2, 3, 4, 5, 6],inplace=True)
df_math_mid.drop(["Unnamed: 0", "Unnamed: 2", "Unnamed: 4"], axis=1, inplace=True)
df_math_mid.rename(columns={'Academic Year 2025/2026' : 'ID', 'Unnamed: 3' : 'Math midterm'}, inplace=True)
df_math_mid

          ID Math midterm
7   22423021         3,50
8   22423178         5,25
9   22423324        12,75
10  22422983         2,50
11  22423198         4,75
..       ...          ...
65  22423199        16,25
66  22423337         8,75
67  22423230        12,50
68  22423304        11,75
69  22423244         7,00

[63 rows x 2 columns]

In [31]:
#df_math_mid['ID'] = df_math_mid['ID'].astype(str).str.strip()

In [32]:
df = pd.merge(df, df_math_mid, on="ID")
df

,ID,French Midterm 1,French Final,French Oral,CSPC midterm,CSPC Final,CSPC PW,DSA total,Math midterm
0,22423021,17,18.5,"17,5",18.667,10.8355,15.769231,12,"3,50"
1,22423178,13,15.5,15,14.001,12.835,18.076923,16.1,"5,25"
2,22423324,17,15,"17,75",18.667,12.1685,19.230769,15.5,"12,75"
3,22422983,19,11.5,14,12.002,7.002,15.897436,16.2,"2,50"
4,22423198,15,13.5,16,12.335,7.8345,15.769231,12.3,"4,75"
...,...,...,...,...,...,...,...,...,...
61,22423199,18,18,17,14.668,12.6685,11.645833,14.8,"16,25"
62,22423337,"10,5",16,12.5,14.668,14.0015,11.270833,12.3,"8,75"
63,22423230,16,20,19.5,16.334,10.002,8.75,14.3,"12,50"
64,22423304,"18,5",17,18,14.668,13.168,13.020833,12.8,"11,75"
65,22423244,"18,5",20,16.5,14.668,11.1685,10.729167,11.6,"7,00"

In [33]:
df[df['ID'] == 22423005]

,ID,French Midterm 1,French Final,French Oral,CSPC midterm,CSPC Final,CSPC PW,DSA total,Math midterm
20,22423005,19,18,19,18.667,15.3345,17.777778,17.7,"15,00"

## AOM Midterm

In [34]:
df_aom_mid = pd.read_excel("grades/AOM-1-CC1_2025-2026 sts.xlsx", sheet_name="CS")
df_aom_mid

   Unnamed: 0 Academic Year 2025/2026 Unnamed: 2 Unnamed: 3 Unnamed: 4
0         NaN                     NaN        NaN        NaN        NaN
1         NaN     Computer science L1        NaN        NaN        NaN
2         NaN                     NaN        NaN        NaN        NaN
3         NaN              Semester 1      AOM-1        NaN        NaN
4         NaN                     NaN        NaN        NaN        NaN
..        ...                     ...        ...        ...        ...
66         28                22423337      12.31        NaN        NaN
67         29                22423230      12.31        NaN        NaN
68         30                22423304       7.69        NaN        NaN
69         31                22423244      10.77        NaN        NaN
70        NaN                     NaN   11.42206        NaN        NaN

[71 rows x 5 columns]

In [35]:
df_aom_mid.drop([0, 1, 2, 3, 4, 5, 6],inplace=True)
df_aom_mid.drop(["Unnamed: 0", "Unnamed: 3", "Unnamed: 4"], axis=1, inplace=True)
df_aom_mid.rename(columns={'Academic Year 2025/2026' : 'ID', 'Unnamed: 2' : 'AOM midterm'}, inplace=True)
df_aom_mid

          ID AOM midterm
7   22423021    9.615385
8   22423178    7.884615
9   22423324   14.807692
10  22422983         8.5
11  22423198    2.884615
..       ...         ...
66  22423337       12.31
67  22423230       12.31
68  22423304        7.69
69  22423244       10.77
70       NaN    11.42206

[64 rows x 2 columns]

In [36]:
df = pd.merge(df, df_aom_mid, on="ID")
df

,ID,French Midterm 1,French Final,French Oral,CSPC midterm,CSPC Final,CSPC PW,DSA total,Math midterm,AOM midterm
0,22423021,17,18.5,"17,5",18.667,10.8355,15.769231,12,"3,50",9.615385
1,22423178,13,15.5,15,14.001,12.835,18.076923,16.1,"5,25",7.884615
2,22423324,17,15,"17,75",18.667,12.1685,19.230769,15.5,"12,75",14.807692
3,22422983,19,11.5,14,12.002,7.002,15.897436,16.2,"2,50",8.5
4,22423198,15,13.5,16,12.335,7.8345,15.769231,12.3,"4,75",2.884615
...,...,...,...,...,...,...,...,...,...,...
65,22423199,18,18,17,14.668,12.6685,11.645833,14.8,"16,25",13.46
66,22423337,"10,5",16,12.5,14.668,14.0015,11.270833,12.3,"8,75",12.31
67,22423230,16,20,19.5,16.334,10.002,8.75,14.3,"12,50",12.31
68,22423304,"18,5",17,18,14.668,13.168,13.020833,12.8,"11,75",7.69
69,22423244,"18,5",20,16.5,14.668,11.1685,10.729167,11.6,"7,00",10.77

In [37]:
df[df['ID'] == 22423005]

,ID,French Midterm 1,French Final,French Oral,CSPC midterm,CSPC Final,CSPC PW,DSA total,Math midterm,AOM midterm
20,22423005,19,18,19,18.667,15.3345,17.777778,17.7,"15,00",15.769231

## AOM Final

In [38]:
df_aom_final = pd.read_excel("grades/L1 Grades - AOM-1-CC1_2025-2026.xlsx")
df_aom_final

   Unnamed: 0 Academic Year 2025/2026 Unnamed: 2 Unnamed: 3 Unnamed: 4
0         NaN                     NaN        NaN        NaN        NaN
1         NaN     Computer science L1        NaN        NaN        NaN
2         NaN                     NaN        NaN        NaN        NaN
3         NaN              Semester 1        NaN        NaN        NaN
4         NaN                     NaN        NaN        NaN        NaN
..        ...                     ...        ...        ...        ...
65         27                22423199      13.46      10.56  11.526667
66         28                22423337      12.31         10      10.77
67         29                22423230      12.31        3.7       6.57
68         30                22423304       7.69       6.06   6.603333
69         31                22423244      10.77       8.15   9.023333

[70 rows x 5 columns]

In [39]:
df_aom_final.drop([0, 1, 2, 3, 4, 5, 6],inplace=True)
df_aom_final.drop(["Unnamed: 0", "Unnamed: 2", "Unnamed: 4"], axis=1, inplace=True)
df_aom_final.rename(columns={'Academic Year 2025/2026' : 'ID', 'Unnamed: 3' : 'AOM final'}, inplace=True)
df_aom_final

          ID AOM final
7   22423021      4.81
8   22423178     12.23
9   22423324     17.67
10  22422983      4.07
11  22423198      2.22
..       ...       ...
65  22423199     10.56
66  22423337        10
67  22423230       3.7
68  22423304      6.06
69  22423244      8.15

[63 rows x 2 columns]

In [40]:
df = pd.merge(df, df_aom_final, on="ID")
df

,ID,French Midterm 1,French Final,French Oral,CSPC midterm,CSPC Final,CSPC PW,DSA total,Math midterm,AOM midterm,AOM final
0,22423021,17,18.5,"17,5",18.667,10.8355,15.769231,12,"3,50",9.615385,4.81
1,22423178,13,15.5,15,14.001,12.835,18.076923,16.1,"5,25",7.884615,12.23
2,22423324,17,15,"17,75",18.667,12.1685,19.230769,15.5,"12,75",14.807692,17.67
3,22422983,19,11.5,14,12.002,7.002,15.897436,16.2,"2,50",8.5,4.07
4,22423198,15,13.5,16,12.335,7.8345,15.769231,12.3,"4,75",2.884615,2.22
...,...,...,...,...,...,...,...,...,...,...,...
65,22423199,18,18,17,14.668,12.6685,11.645833,14.8,"16,25",13.46,10.56
66,22423337,"10,5",16,12.5,14.668,14.0015,11.270833,12.3,"8,75",12.31,10
67,22423230,16,20,19.5,16.334,10.002,8.75,14.3,"12,50",12.31,3.7
68,22423304,"18,5",17,18,14.668,13.168,13.020833,12.8,"11,75",7.69,6.06
69,22423244,"18,5",20,16.5,14.668,11.1685,10.729167,11.6,"7,00",10.77,8.15

## Thermodynamics exam

In [41]:
df_thermo = pd.read_excel("grades/L1_24 Thermodynamics-1.xlsx", sheet_name="CS")
df_thermo

   Unnamed: 0 Academic Year 2025/2026 Unnamed: 2 Unnamed: 3 Unnamed: 4
0         NaN                     NaN        NaN        NaN        NaN
1         NaN     Computer science L1        NaN        NaN        NaN
2         NaN                     NaN        NaN        NaN        NaN
3         NaN              Semester 1        NaN        NaN        NaN
4         NaN                     NaN        NaN        NaN        NaN
..        ...                     ...        ...        ...        ...
65         27                22423199      10.55        NaN        NaN
66         28                22423337      12.25        NaN        NaN
67         29                22423230       5.75        NaN        NaN
68         30                22423304        8.8        NaN        NaN
69         31                22423244          4        NaN        NaN

[70 rows x 5 columns]

In [42]:
df_thermo.drop([0, 1, 2, 3, 4, 5, 6],inplace=True)
df_thermo.drop(["Unnamed: 0", "Unnamed: 3", "Unnamed: 4"], axis=1, inplace=True)
df_thermo.rename(columns={'Academic Year 2025/2026' : 'ID', 'Unnamed: 2' : 'Thermodynamics'}, inplace=True)
df_thermo

          ID Thermodynamics
7   22423021           8.75
8   22423178          14.25
9   22423324             11
10  22422983            0.5
11  22423198              5
..       ...            ...
65  22423199          10.55
66  22423337          12.25
67  22423230           5.75
68  22423304            8.8
69  22423244              4

[63 rows x 2 columns]

In [43]:
df = pd.merge(df, df_thermo, on="ID")
df

,ID,French Midterm 1,French Final,French Oral,CSPC midterm,CSPC Final,CSPC PW,DSA total,Math midterm,AOM midterm,AOM final,Thermodynamics
0,22423021,17,18.5,"17,5",18.667,10.8355,15.769231,12,"3,50",9.615385,4.81,8.75
1,22423178,13,15.5,15,14.001,12.835,18.076923,16.1,"5,25",7.884615,12.23,14.25
2,22423324,17,15,"17,75",18.667,12.1685,19.230769,15.5,"12,75",14.807692,17.67,11
3,22422983,19,11.5,14,12.002,7.002,15.897436,16.2,"2,50",8.5,4.07,0.5
4,22423198,15,13.5,16,12.335,7.8345,15.769231,12.3,"4,75",2.884615,2.22,5
...,...,...,...,...,...,...,...,...,...,...,...,...
65,22423199,18,18,17,14.668,12.6685,11.645833,14.8,"16,25",13.46,10.56,10.55
66,22423337,"10,5",16,12.5,14.668,14.0015,11.270833,12.3,"8,75",12.31,10,12.25
67,22423230,16,20,19.5,16.334,10.002,8.75,14.3,"12,50",12.31,3.7,5.75
68,22423304,"18,5",17,18,14.668,13.168,13.020833,12.8,"11,75",7.69,6.06,8.8
69,22423244,"18,5",20,16.5,14.668,11.1685,10.729167,11.6,"7,00",10.77,8.15,4

In [44]:
df[df['ID'] == 22423005]

,ID,French Midterm 1,French Final,French Oral,CSPC midterm,CSPC Final,CSPC PW,DSA total,Math midterm,AOM midterm,AOM final,Thermodynamics
20,22423005,19,18,19,18.667,15.3345,17.777778,17.7,"15,00",15.769231,12.97,16

## Point Mechanics Exam

In [45]:
df_pointmech = pd.read_excel("grades/L1-024 Grade for Point Mechanics.xlsx", sheet_name="CS")
df_pointmech

   Unnamed: 0 Academic Year 2025/2026       Unnamed: 2 Unnamed: 3 Unnamed: 4
0         NaN                     NaN              NaN        NaN        NaN
1         NaN     Computer science L1              NaN        NaN        NaN
2         NaN                     NaN              NaN        NaN        NaN
3         NaN              Semester 1  Point Mechanics        NaN        NaN
4         NaN                     NaN              NaN        NaN        NaN
..        ...                     ...              ...        ...        ...
72         29                22423230             2.64        1.8       4.44
73         30                22423304                0          0          0
74         31                22423244             4.92          0       4.92
75        NaN                     NaN              NaN        NaN        NaN
76        NaN                     NaN              NaN    Average   6.058667

[77 rows x 5 columns]

In [46]:
df_pointmech.drop([0, 1, 2, 3, 4, 5, 6, 7],inplace=True)
df_pointmech.drop(["Unnamed: 0", "Unnamed: 2", "Unnamed: 3"], axis=1, inplace=True)
df_pointmech.rename(columns={'Academic Year 2025/2026' : 'ID', 'Unnamed: 4' : 'Point Mechanics'}, inplace=True)
df_pointmech

          ID Point Mechanics
8   22423021            4.32
9   22423178            11.4
10  22423324            12.6
11  22422983              ab
12  22423198            3.84
..       ...             ...
72  22423230            4.44
73  22423304               0
74  22423244            4.92
75       NaN             NaN
76       NaN        6.058667

[69 rows x 2 columns]

In [47]:
df = pd.merge(df, df_pointmech, on="ID")
df

,ID,French Midterm 1,French Final,French Oral,CSPC midterm,CSPC Final,CSPC PW,DSA total,Math midterm,AOM midterm,AOM final,Thermodynamics,Point Mechanics
0,22423021,17,18.5,"17,5",18.667,10.8355,15.769231,12,"3,50",9.615385,4.81,8.75,4.32
1,22423178,13,15.5,15,14.001,12.835,18.076923,16.1,"5,25",7.884615,12.23,14.25,11.4
2,22423324,17,15,"17,75",18.667,12.1685,19.230769,15.5,"12,75",14.807692,17.67,11,12.6
3,22422983,19,11.5,14,12.002,7.002,15.897436,16.2,"2,50",8.5,4.07,0.5,ab
4,22423198,15,13.5,16,12.335,7.8345,15.769231,12.3,"4,75",2.884615,2.22,5,3.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,22423199,18,18,17,14.668,12.6685,11.645833,14.8,"16,25",13.46,10.56,10.55,2.34
114,22423337,"10,5",16,12.5,14.668,14.0015,11.270833,12.3,"8,75",12.31,10,12.25,1.2
115,22423230,16,20,19.5,16.334,10.002,8.75,14.3,"12,50",12.31,3.7,5.75,4.44
116,22423304,"18,5",17,18,14.668,13.168,13.020833,12.8,"11,75",7.69,6.06,8.8,0
117,22423244,"18,5",20,16.5,14.668,11.1685,10.729167,11.6,"7,00",10.77,8.15,4,4.92

In [48]:
df[df['ID'].notna()].count()

ID                  62
French Midterm 1    62
French Final        62
French Oral         62
CSPC midterm        62
CSPC Final          62
CSPC PW             62
DSA total           61
Math midterm        62
AOM midterm         59
AOM final           61
Thermodynamics      60
Point Mechanics     62
dtype: int64

In [49]:
df.count()

ID                  62
French Midterm 1    62
French Final        62
French Oral         62
CSPC midterm        62
CSPC Final          62
CSPC PW             62
DSA total           61
Math midterm        62
AOM midterm         87
AOM final           61
Thermodynamics      60
Point Mechanics     86
dtype: int64

In [50]:
df[df['ID'] == 22423005]

,ID,French Midterm 1,French Final,French Oral,CSPC midterm,CSPC Final,CSPC PW,DSA total,Math midterm,AOM midterm,AOM final,Thermodynamics,Point Mechanics
20,22423005,19,18,19,18.667,15.3345,17.777778,17.7,"15,00",15.769231,12.97,16,18

## Front-end Exam

In [51]:
dfs = tabula.read_pdf('grades/FrontEndFInal.pdf', pages='all')

Failed to import jpype dependencies. Fallback to subprocess.
No module named 'jpype'

In [52]:
dfs

[   S.No. UNISTRA card\rNo.        Surname Name  CC1  CC2   CC3
 0    NaN             Coef.                 NaN  NaN  NaN   NaN
 1      1          22423021       Abbasli Fidan  NaN  NaN  12.5
 2      2          22423178     Abbasli Ismayil  NaN  NaN  13.1
 3      3          22423324     Abbaszada Tunar  NaN  NaN  10.1
 4      4          22422983   Abdurahmanov Amir  NaN  NaN   NaN
 5      5          22423198    Abishov Mahammad  NaN  NaN   8.9
 6      6          22423293    Aghamaliyev Said  NaN  NaN  13.1
 7      7          22423258      Ahmadzada Raul  NaN  NaN  11.9
 8      8          22423161     Akhundova Gunay  NaN  NaN  15.5
 9      9          22423200    Akhundova Maryam  NaN  NaN  16.1
 10    10          22423307    Alasgarov Teymur  NaN  NaN  13.7
 11    11          22423174      Algayeva Ilaha  NaN  NaN  13.1
 12    12          22322620  Alı̇pashayev Ravan  NaN  NaN   NaN
 13    13          22422997        Aliyev Elnur  NaN  NaN   NaN
 14    14          22423162        Aliyev Hakim  NaN  NaN  13.1
 15    15          22423312       Alizada Tofig  NaN  NaN  16.7
 16    16          22423242       Asadli Nasrin  NaN  NaN  19.8
 17    17          22423208    Atlukhanov Murad  NaN  NaN  16.7
 18    18          22423213        Azizov Nadir  NaN  NaN  14.3
 19    19          22423163      Balayev Huseyn  NaN  NaN  10.1
 20    20          22423185      Bayramli Javid  NaN  NaN  13.7
 21    21          22423005      Budagov Farhad  NaN  NaN  16.1
 22    22          22423010   Burjaliyev Farhad  NaN  NaN  15.5
 23    23          22423280      Garibov Sabuhi  NaN  NaN  13.7
 24    24          22322607       Gasimov Murad  NaN  NaN   8.2
 25    25          22423203     Guliyev Mikayil  NaN  NaN  14.3
 26    26          22423001   Gulmammadov Famil  NaN  NaN  10.1
 27    27          22423333   Haji-Nabili Tural  NaN  NaN  11.9
 28    28          22422990      Hajiyev Bahruz  NaN  NaN  10.7
 29    29          22423190       Hasanli Kamil  NaN  NaN  16.1
 30    30          22423301     Hasanova Tamara  NaN  NaN  14.9
 31    31          22423282       Hasratli Said  NaN  NaN  16.1
 32   CS1               NaN                 NaN  NaN  NaN   NaN
 33     1          22423192     Huseynli Kamran  NaN  NaN  11.9,
        9    3  3.1    15   9.1  12.5
 0    7.0  3.0  6.0  16.0   9.7  13.1
 1    7.0  3.0  1.0  11.0   6.7  10.1
 2    NaN  NaN  NaN   NaN   NaN   NaN
 3    3.0  4.0  2.0   9.0   5.5   8.9
 4    7.0  3.0  6.0  16.0   9.7  13.1
 5    5.0  7.0  2.0  14.0   8.5  11.9
 6    9.0  6.0  5.0  20.0  12.1  15.5
 7   10.0  7.0  4.0  21.0  12.7  16.1
 8    7.0  6.0  4.0  17.0  10.3  13.7
 9    6.0  4.0  6.0  16.0   9.7  13.1
 10   NaN  NaN  NaN   NaN   NaN   NaN
 11   NaN  NaN  NaN   NaN   NaN   NaN
 12   7.0  5.0  4.0  16.0   9.7  13.1
 13  10.0  5.0  7.0  22.0  13.3  16.7
 14  13.0  6.0  8.0  27.0  16.4  19.8
 15   8.0  7.0  7.0  22.0  13.3  16.7
 16   8.0  8.0  2.0  18.0  10.9  14.3
 17   5.0  3.0  3.0  11.0   6.7  10.1
 18  11.0  2.0  4.0  17.0  10.3  13.7
 19  11.0  5.0  5.0  21.0  12.7  16.1
 20   8.0  6.0  6.0  20.0  12.1  15.5
 21   7.0  5.0  5.0  17.0  10.3  13.7
 22   4.0  2.0  2.0   8.0   4.8   8.2
 23   7.0  5.0  6.0  18.0  10.9  14.3
 24   4.0  3.0  4.0  11.0   6.7  10.1
 25  10.0  4.0  NaN  14.0   8.5  11.9
 26   7.0  2.0  3.0  12.0   7.3  10.7
 27   9.0  6.0  6.0  21.0  12.7  16.1
 28   9.0  4.0  6.0  19.0  11.5  14.9
 29  10.0  6.0  5.0  21.0  12.7  16.1
 30   NaN  NaN  NaN   NaN   NaN   NaN
 31   7.0  2.0  5.0  14.0   8.5  11.9,
      2  22423251      Ilyasli Nilufar  Unnamed: 0  Unnamed: 1  14.9
 0    3  22422989       Jafarova Aziza         NaN         NaN  14.3
 1    4  22423196   Javadzade Mahammad         NaN         NaN  16.7
 2    5  22423334       Khalafli Yusif         NaN         NaN  14.9
 3    6  22423318  Khankishizade Tunar         NaN         NaN   7.6
 4    7  22422993    Kuchinskiy Daniil         NaN         NaN   9.5
 5    8  22422979        Majidzade Ali         NaN         NaN  15.5
 6    9  22423023       Mammadli Fidan         NaN         NaN  11.9
 7   10  22423157      Mammadli Gulzar         NaN         NaN   8.9
 8   11  22422999       Mammadov Elsel         NaN         NaN   9.5
 9   12  22423156      Mammadova Fatma         NaN         NaN  14.3
 10  13  22425334   Mohammad Bakir Isa         NaN         NaN  12.5
 11  14  22422996     Mutallimov Eldar         NaN         NaN  12.5
 12  15  22423182      Najafzade Jansu         NaN         NaN  11.9
 13  16  22423260      Rahimbayov Riad         NaN         NaN  12.5
 14  17  22423169        Rahimli Igbal         NaN         NaN  14.9
 15  18  22423257        Rahimov Rasul         NaN         NaN  16.7
 16  19  22322638      Rashıḋlı ̇Yusif         NaN         NaN   8.9
 17  20  22423252          Rzali Nuray         NaN         NaN   8.9
 18  21  22423234      Rzayeva Narmina         NaN         NaN  15.5
 19  22  22422986        Safarov Ayhan         NaN         NaN  13.7
 20  23  22423254       Salahov Parvin         NaN         NaN  14.9
 21  24  22423295         Salahov Sami         NaN         NaN  10.1
 22  25  22423233       Seyidli Narmin         NaN         NaN  10.7
 23  26  22423238    Sharifova Narmina         NaN         NaN  13.1
 24  27  22423199    Taghiyeva Mahsati         NaN         NaN  11.3
 25  28  22423337         Valiyev Zaur         NaN         NaN  13.7
 26  29  22423230     Yusibzada Narmin         NaN         NaN  16.1
 27  30  22423304       Yusubov Telman         NaN         NaN  10.7
 28  31  22423244      Zahidova Nazrin         NaN         NaN   8.9,
          10      4     5    19  11.5  14.9
 0         7   5.00   6.0  18.0  10.9  14.3
 1         9   6.00   7.0  22.0  13.3  16.7
 2         8   5.00   6.0  19.0  11.5  14.9
 3         4   1.00   2.0   7.0   4.2   7.6
 4         5   3.00   2.0  10.0   6.1   9.5
 5         8   6.00   6.0  20.0  12.1  15.5
 6         7   2.00   5.0  14.0   8.5  11.9
 7         6   0.00   3.0   9.0   5.5   8.9
 8         5   2.00   3.0  10.0   6.1   9.5
 9         9   3.00   6.0  18.0  10.9  14.3
 10        8   3.00   4.0  15.0   9.1  12.5
 11        8   4.00   3.0  15.0   9.1  12.5
 12        8   3.00   3.0  14.0   8.5  11.9
 13        9   5.00   1.0  15.0   9.1  12.5
 14       11   3.00   5.0  19.0  11.5  14.9
 15        9   8.00   5.0  22.0  13.3  16.7
 16        7   0.00   2.0   9.0   5.5   8.9
 17        5   1.00   3.0   9.0   5.5   8.9
 18        7   6.00   7.0  20.0  12.1  15.5
 19        7   4.00   6.0  17.0  10.3  13.7
 20        8   5.00   6.0  19.0  11.5  14.9
 21        6   2.00   3.0  11.0   6.7  10.1
 22        6   1.00   5.0  12.0   7.3  10.7
 23        7   1.00   8.0  16.0   9.7  13.1
 24       10   2.00   1.0  13.0   7.9  11.3
 25        6   6.00   5.0  17.0  10.3  13.7
 26        8   7.00   6.0  21.0  12.7  16.1
 27        8   2.00   2.0  12.0   7.3  10.7
 28        5   0.00   4.0   9.0   5.5   8.9
 29      AVG   9.61  13.0   NaN   NaN   NaN
 30    STDEV   2.70   2.7   NaN   NaN   NaN
 31  Nb >=10  28.00  50.0   NaN   NaN   NaN]

In [53]:
dfs[0] #cs1

   S.No. UNISTRA card\rNo.        Surname Name  CC1  CC2   CC3
0    NaN             Coef.                 NaN  NaN  NaN   NaN
1      1          22423021       Abbasli Fidan  NaN  NaN  12.5
2      2          22423178     Abbasli Ismayil  NaN  NaN  13.1
3      3          22423324     Abbaszada Tunar  NaN  NaN  10.1
4      4          22422983   Abdurahmanov Amir  NaN  NaN   NaN
5      5          22423198    Abishov Mahammad  NaN  NaN   8.9
6      6          22423293    Aghamaliyev Said  NaN  NaN  13.1
7      7          22423258      Ahmadzada Raul  NaN  NaN  11.9
8      8          22423161     Akhundova Gunay  NaN  NaN  15.5
9      9          22423200    Akhundova Maryam  NaN  NaN  16.1
10    10          22423307    Alasgarov Teymur  NaN  NaN  13.7
11    11          22423174      Algayeva Ilaha  NaN  NaN  13.1
12    12          22322620  Alı̇pashayev Ravan  NaN  NaN   NaN
13    13          22422997        Aliyev Elnur  NaN  NaN   NaN
14    14          22423162        Aliyev Hakim  NaN  NaN  13.1
15    15          22423312       Alizada Tofig  NaN  NaN  16.7
16    16          22423242       Asadli Nasrin  NaN  NaN  19.8
17    17          22423208    Atlukhanov Murad  NaN  NaN  16.7
18    18          22423213        Azizov Nadir  NaN  NaN  14.3
19    19          22423163      Balayev Huseyn  NaN  NaN  10.1
20    20          22423185      Bayramli Javid  NaN  NaN  13.7
21    21          22423005      Budagov Farhad  NaN  NaN  16.1
22    22          22423010   Burjaliyev Farhad  NaN  NaN  15.5
23    23          22423280      Garibov Sabuhi  NaN  NaN  13.7
24    24          22322607       Gasimov Murad  NaN  NaN   8.2
25    25          22423203     Guliyev Mikayil  NaN  NaN  14.3
26    26          22423001   Gulmammadov Famil  NaN  NaN  10.1
27    27          22423333   Haji-Nabili Tural  NaN  NaN  11.9
28    28          22422990      Hajiyev Bahruz  NaN  NaN  10.7
29    29          22423190       Hasanli Kamil  NaN  NaN  16.1
30    30          22423301     Hasanova Tamara  NaN  NaN  14.9
31    31          22423282       Hasratli Said  NaN  NaN  16.1
32   CS1               NaN                 NaN  NaN  NaN   NaN
33     1          22423192     Huseynli Kamran  NaN  NaN  11.9

In [54]:
dfs[2] #cs2

     2  22423251      Ilyasli Nilufar  Unnamed: 0  Unnamed: 1  14.9
0    3  22422989       Jafarova Aziza         NaN         NaN  14.3
1    4  22423196   Javadzade Mahammad         NaN         NaN  16.7
2    5  22423334       Khalafli Yusif         NaN         NaN  14.9
3    6  22423318  Khankishizade Tunar         NaN         NaN   7.6
4    7  22422993    Kuchinskiy Daniil         NaN         NaN   9.5
5    8  22422979        Majidzade Ali         NaN         NaN  15.5
6    9  22423023       Mammadli Fidan         NaN         NaN  11.9
7   10  22423157      Mammadli Gulzar         NaN         NaN   8.9
8   11  22422999       Mammadov Elsel         NaN         NaN   9.5
9   12  22423156      Mammadova Fatma         NaN         NaN  14.3
10  13  22425334   Mohammad Bakir Isa         NaN         NaN  12.5
11  14  22422996     Mutallimov Eldar         NaN         NaN  12.5
12  15  22423182      Najafzade Jansu         NaN         NaN  11.9
13  16  22423260      Rahimbayov Riad         NaN         NaN  12.5
14  17  22423169        Rahimli Igbal         NaN         NaN  14.9
15  18  22423257        Rahimov Rasul         NaN         NaN  16.7
16  19  22322638      Rashıḋlı ̇Yusif         NaN         NaN   8.9
17  20  22423252          Rzali Nuray         NaN         NaN   8.9
18  21  22423234      Rzayeva Narmina         NaN         NaN  15.5
19  22  22422986        Safarov Ayhan         NaN         NaN  13.7
20  23  22423254       Salahov Parvin         NaN         NaN  14.9
21  24  22423295         Salahov Sami         NaN         NaN  10.1
22  25  22423233       Seyidli Narmin         NaN         NaN  10.7
23  26  22423238    Sharifova Narmina         NaN         NaN  13.1
24  27  22423199    Taghiyeva Mahsati         NaN         NaN  11.3
25  28  22423337         Valiyev Zaur         NaN         NaN  13.7
26  29  22423230     Yusibzada Narmin         NaN         NaN  16.1
27  30  22423304       Yusubov Telman         NaN         NaN  10.7
28  31  22423244      Zahidova Nazrin         NaN         NaN   8.9

In [55]:
df_frontEnd_exam_part1 = pd.DataFrame(dfs[0])
df_frontEnd_exam_part1

   S.No. UNISTRA card\rNo.        Surname Name  CC1  CC2   CC3
0    NaN             Coef.                 NaN  NaN  NaN   NaN
1      1          22423021       Abbasli Fidan  NaN  NaN  12.5
2      2          22423178     Abbasli Ismayil  NaN  NaN  13.1
3      3          22423324     Abbaszada Tunar  NaN  NaN  10.1
4      4          22422983   Abdurahmanov Amir  NaN  NaN   NaN
5      5          22423198    Abishov Mahammad  NaN  NaN   8.9
6      6          22423293    Aghamaliyev Said  NaN  NaN  13.1
7      7          22423258      Ahmadzada Raul  NaN  NaN  11.9
8      8          22423161     Akhundova Gunay  NaN  NaN  15.5
9      9          22423200    Akhundova Maryam  NaN  NaN  16.1
10    10          22423307    Alasgarov Teymur  NaN  NaN  13.7
11    11          22423174      Algayeva Ilaha  NaN  NaN  13.1
12    12          22322620  Alı̇pashayev Ravan  NaN  NaN   NaN
13    13          22422997        Aliyev Elnur  NaN  NaN   NaN
14    14          22423162        Aliyev Hakim  NaN  NaN  13.1
15    15          22423312       Alizada Tofig  NaN  NaN  16.7
16    16          22423242       Asadli Nasrin  NaN  NaN  19.8
17    17          22423208    Atlukhanov Murad  NaN  NaN  16.7
18    18          22423213        Azizov Nadir  NaN  NaN  14.3
19    19          22423163      Balayev Huseyn  NaN  NaN  10.1
20    20          22423185      Bayramli Javid  NaN  NaN  13.7
21    21          22423005      Budagov Farhad  NaN  NaN  16.1
22    22          22423010   Burjaliyev Farhad  NaN  NaN  15.5
23    23          22423280      Garibov Sabuhi  NaN  NaN  13.7
24    24          22322607       Gasimov Murad  NaN  NaN   8.2
25    25          22423203     Guliyev Mikayil  NaN  NaN  14.3
26    26          22423001   Gulmammadov Famil  NaN  NaN  10.1
27    27          22423333   Haji-Nabili Tural  NaN  NaN  11.9
28    28          22422990      Hajiyev Bahruz  NaN  NaN  10.7
29    29          22423190       Hasanli Kamil  NaN  NaN  16.1
30    30          22423301     Hasanova Tamara  NaN  NaN  14.9
31    31          22423282       Hasratli Said  NaN  NaN  16.1
32   CS1               NaN                 NaN  NaN  NaN   NaN
33     1          22423192     Huseynli Kamran  NaN  NaN  11.9

In [56]:
df_frontEnd_exam_part2 = pd.DataFrame(dfs[2])
df_frontEnd_exam_part2

     2  22423251      Ilyasli Nilufar  Unnamed: 0  Unnamed: 1  14.9
0    3  22422989       Jafarova Aziza         NaN         NaN  14.3
1    4  22423196   Javadzade Mahammad         NaN         NaN  16.7
2    5  22423334       Khalafli Yusif         NaN         NaN  14.9
3    6  22423318  Khankishizade Tunar         NaN         NaN   7.6
4    7  22422993    Kuchinskiy Daniil         NaN         NaN   9.5
5    8  22422979        Majidzade Ali         NaN         NaN  15.5
6    9  22423023       Mammadli Fidan         NaN         NaN  11.9
7   10  22423157      Mammadli Gulzar         NaN         NaN   8.9
8   11  22422999       Mammadov Elsel         NaN         NaN   9.5
9   12  22423156      Mammadova Fatma         NaN         NaN  14.3
10  13  22425334   Mohammad Bakir Isa         NaN         NaN  12.5
11  14  22422996     Mutallimov Eldar         NaN         NaN  12.5
12  15  22423182      Najafzade Jansu         NaN         NaN  11.9
13  16  22423260      Rahimbayov Riad         NaN         NaN  12.5
14  17  22423169        Rahimli Igbal         NaN         NaN  14.9
15  18  22423257        Rahimov Rasul         NaN         NaN  16.7
16  19  22322638      Rashıḋlı ̇Yusif         NaN         NaN   8.9
17  20  22423252          Rzali Nuray         NaN         NaN   8.9
18  21  22423234      Rzayeva Narmina         NaN         NaN  15.5
19  22  22422986        Safarov Ayhan         NaN         NaN  13.7
20  23  22423254       Salahov Parvin         NaN         NaN  14.9
21  24  22423295         Salahov Sami         NaN         NaN  10.1
22  25  22423233       Seyidli Narmin         NaN         NaN  10.7
23  26  22423238    Sharifova Narmina         NaN         NaN  13.1
24  27  22423199    Taghiyeva Mahsati         NaN         NaN  11.3
25  28  22423337         Valiyev Zaur         NaN         NaN  13.7
26  29  22423230     Yusibzada Narmin         NaN         NaN  16.1
27  30  22423304       Yusubov Telman         NaN         NaN  10.7
28  31  22423244      Zahidova Nazrin         NaN         NaN   8.9

In [57]:
datarow = df_frontEnd_exam_part2.columns.to_series()
datarow = pd.DataFrame(datarow)
datarow = datarow.T
datarow.columns = df_frontEnd_exam_part1.columns

In [58]:
datarow

  S.No. UNISTRA card\rNo.     Surname Name         CC1         CC2   CC3
0     2          22423251  Ilyasli Nilufar  Unnamed: 0  Unnamed: 1  14.9

In [59]:
df_frontEnd_exam_part1

   S.No. UNISTRA card\rNo.        Surname Name  CC1  CC2   CC3
0    NaN             Coef.                 NaN  NaN  NaN   NaN
1      1          22423021       Abbasli Fidan  NaN  NaN  12.5
2      2          22423178     Abbasli Ismayil  NaN  NaN  13.1
3      3          22423324     Abbaszada Tunar  NaN  NaN  10.1
4      4          22422983   Abdurahmanov Amir  NaN  NaN   NaN
5      5          22423198    Abishov Mahammad  NaN  NaN   8.9
6      6          22423293    Aghamaliyev Said  NaN  NaN  13.1
7      7          22423258      Ahmadzada Raul  NaN  NaN  11.9
8      8          22423161     Akhundova Gunay  NaN  NaN  15.5
9      9          22423200    Akhundova Maryam  NaN  NaN  16.1
10    10          22423307    Alasgarov Teymur  NaN  NaN  13.7
11    11          22423174      Algayeva Ilaha  NaN  NaN  13.1
12    12          22322620  Alı̇pashayev Ravan  NaN  NaN   NaN
13    13          22422997        Aliyev Elnur  NaN  NaN   NaN
14    14          22423162        Aliyev Hakim  NaN  NaN  13.1
15    15          22423312       Alizada Tofig  NaN  NaN  16.7
16    16          22423242       Asadli Nasrin  NaN  NaN  19.8
17    17          22423208    Atlukhanov Murad  NaN  NaN  16.7
18    18          22423213        Azizov Nadir  NaN  NaN  14.3
19    19          22423163      Balayev Huseyn  NaN  NaN  10.1
20    20          22423185      Bayramli Javid  NaN  NaN  13.7
21    21          22423005      Budagov Farhad  NaN  NaN  16.1
22    22          22423010   Burjaliyev Farhad  NaN  NaN  15.5
23    23          22423280      Garibov Sabuhi  NaN  NaN  13.7
24    24          22322607       Gasimov Murad  NaN  NaN   8.2
25    25          22423203     Guliyev Mikayil  NaN  NaN  14.3
26    26          22423001   Gulmammadov Famil  NaN  NaN  10.1
27    27          22423333   Haji-Nabili Tural  NaN  NaN  11.9
28    28          22422990      Hajiyev Bahruz  NaN  NaN  10.7
29    29          22423190       Hasanli Kamil  NaN  NaN  16.1
30    30          22423301     Hasanova Tamara  NaN  NaN  14.9
31    31          22423282       Hasratli Said  NaN  NaN  16.1
32   CS1               NaN                 NaN  NaN  NaN   NaN
33     1          22423192     Huseynli Kamran  NaN  NaN  11.9

In [60]:
df_frontEnd_exam_part1 = pd.concat([df_frontEnd_exam_part1, datarow])
df_frontEnd_exam_part2.columns = df_frontEnd_exam_part1.columns

In [61]:
df_frontEnd_exam_part1

   S.No. UNISTRA card\rNo.        Surname Name         CC1         CC2   CC3
0    NaN             Coef.                 NaN         NaN         NaN   NaN
1      1          22423021       Abbasli Fidan         NaN         NaN  12.5
2      2          22423178     Abbasli Ismayil         NaN         NaN  13.1
3      3          22423324     Abbaszada Tunar         NaN         NaN  10.1
4      4          22422983   Abdurahmanov Amir         NaN         NaN   NaN
5      5          22423198    Abishov Mahammad         NaN         NaN   8.9
6      6          22423293    Aghamaliyev Said         NaN         NaN  13.1
7      7          22423258      Ahmadzada Raul         NaN         NaN  11.9
8      8          22423161     Akhundova Gunay         NaN         NaN  15.5
9      9          22423200    Akhundova Maryam         NaN         NaN  16.1
10    10          22423307    Alasgarov Teymur         NaN         NaN  13.7
11    11          22423174      Algayeva Ilaha         NaN         NaN  13.1
12    12          22322620  Alı̇pashayev Ravan         NaN         NaN   NaN
13    13          22422997        Aliyev Elnur         NaN         NaN   NaN
14    14          22423162        Aliyev Hakim         NaN         NaN  13.1
15    15          22423312       Alizada Tofig         NaN         NaN  16.7
16    16          22423242       Asadli Nasrin         NaN         NaN  19.8
17    17          22423208    Atlukhanov Murad         NaN         NaN  16.7
18    18          22423213        Azizov Nadir         NaN         NaN  14.3
19    19          22423163      Balayev Huseyn         NaN         NaN  10.1
20    20          22423185      Bayramli Javid         NaN         NaN  13.7
21    21          22423005      Budagov Farhad         NaN         NaN  16.1
22    22          22423010   Burjaliyev Farhad         NaN         NaN  15.5
23    23          22423280      Garibov Sabuhi         NaN         NaN  13.7
24    24          22322607       Gasimov Murad         NaN         NaN   8.2
25    25          22423203     Guliyev Mikayil         NaN         NaN  14.3
26    26          22423001   Gulmammadov Famil         NaN         NaN  10.1
27    27          22423333   Haji-Nabili Tural         NaN         NaN  11.9
28    28          22422990      Hajiyev Bahruz         NaN         NaN  10.7
29    29          22423190       Hasanli Kamil         NaN         NaN  16.1
30    30          22423301     Hasanova Tamara         NaN         NaN  14.9
31    31          22423282       Hasratli Said         NaN         NaN  16.1
32   CS1               NaN                 NaN         NaN         NaN   NaN
33     1          22423192     Huseynli Kamran         NaN         NaN  11.9
0      2          22423251     Ilyasli Nilufar  Unnamed: 0  Unnamed: 1  14.9

In [62]:
df_frontEnd_exam_part2

    S.No.  UNISTRA card\rNo.         Surname Name  CC1  CC2   CC3
0       3           22422989       Jafarova Aziza  NaN  NaN  14.3
1       4           22423196   Javadzade Mahammad  NaN  NaN  16.7
2       5           22423334       Khalafli Yusif  NaN  NaN  14.9
3       6           22423318  Khankishizade Tunar  NaN  NaN   7.6
4       7           22422993    Kuchinskiy Daniil  NaN  NaN   9.5
5       8           22422979        Majidzade Ali  NaN  NaN  15.5
6       9           22423023       Mammadli Fidan  NaN  NaN  11.9
7      10           22423157      Mammadli Gulzar  NaN  NaN   8.9
8      11           22422999       Mammadov Elsel  NaN  NaN   9.5
9      12           22423156      Mammadova Fatma  NaN  NaN  14.3
10     13           22425334   Mohammad Bakir Isa  NaN  NaN  12.5
11     14           22422996     Mutallimov Eldar  NaN  NaN  12.5
12     15           22423182      Najafzade Jansu  NaN  NaN  11.9
13     16           22423260      Rahimbayov Riad  NaN  NaN  12.5
14     17           22423169        Rahimli Igbal  NaN  NaN  14.9
15     18           22423257        Rahimov Rasul  NaN  NaN  16.7
16     19           22322638      Rashıḋlı ̇Yusif  NaN  NaN   8.9
17     20           22423252          Rzali Nuray  NaN  NaN   8.9
18     21           22423234      Rzayeva Narmina  NaN  NaN  15.5
19     22           22422986        Safarov Ayhan  NaN  NaN  13.7
20     23           22423254       Salahov Parvin  NaN  NaN  14.9
21     24           22423295         Salahov Sami  NaN  NaN  10.1
22     25           22423233       Seyidli Narmin  NaN  NaN  10.7
23     26           22423238    Sharifova Narmina  NaN  NaN  13.1
24     27           22423199    Taghiyeva Mahsati  NaN  NaN  11.3
25     28           22423337         Valiyev Zaur  NaN  NaN  13.7
26     29           22423230     Yusibzada Narmin  NaN  NaN  16.1
27     30           22423304       Yusubov Telman  NaN  NaN  10.7
28     31           22423244      Zahidova Nazrin  NaN  NaN   8.9

In [63]:
df_frontEnd_exam = pd.concat([df_frontEnd_exam_part1, df_frontEnd_exam_part2])
df_frontEnd_exam

   S.No. UNISTRA card\rNo.       Surname Name  CC1  CC2   CC3
0    NaN             Coef.                NaN  NaN  NaN   NaN
1      1          22423021      Abbasli Fidan  NaN  NaN  12.5
2      2          22423178    Abbasli Ismayil  NaN  NaN  13.1
3      3          22423324    Abbaszada Tunar  NaN  NaN  10.1
4      4          22422983  Abdurahmanov Amir  NaN  NaN   NaN
..   ...               ...                ...  ...  ...   ...
24    27          22423199  Taghiyeva Mahsati  NaN  NaN  11.3
25    28          22423337       Valiyev Zaur  NaN  NaN  13.7
26    29          22423230   Yusibzada Narmin  NaN  NaN  16.1
27    30          22423304     Yusubov Telman  NaN  NaN  10.7
28    31          22423244    Zahidova Nazrin  NaN  NaN   8.9

[64 rows x 6 columns]

In [64]:
df_frontEnd_exam.drop(['S.No.', 'CC1', 'CC2'], axis=1, inplace=True)
df_frontEnd_exam

   UNISTRA card\rNo.       Surname Name   CC3
0              Coef.                NaN   NaN
1           22423021      Abbasli Fidan  12.5
2           22423178    Abbasli Ismayil  13.1
3           22423324    Abbaszada Tunar  10.1
4           22422983  Abdurahmanov Amir   NaN
..               ...                ...   ...
24          22423199  Taghiyeva Mahsati  11.3
25          22423337       Valiyev Zaur  13.7
26          22423230   Yusibzada Narmin  16.1
27          22423304     Yusubov Telman  10.7
28          22423244    Zahidova Nazrin   8.9

[64 rows x 3 columns]

In [65]:
df_frontEnd_exam['CC3'].fillna(0, inplace=True)
df_frontEnd_exam

/tmp/ipykernel_13964/3904559251.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_frontEnd_exam['CC3'].fillna(0, inplace=True)

   UNISTRA card\rNo.       Surname Name   CC3
0              Coef.                NaN     0
1           22423021      Abbasli Fidan  12.5
2           22423178    Abbasli Ismayil  13.1
3           22423324    Abbaszada Tunar  10.1
4           22422983  Abdurahmanov Amir     0
..               ...                ...   ...
24          22423199  Taghiyeva Mahsati  11.3
25          22423337       Valiyev Zaur  13.7
26          22423230   Yusibzada Narmin  16.1
27          22423304     Yusubov Telman  10.7
28          22423244    Zahidova Nazrin   8.9

[64 rows x 3 columns]

In [66]:
df_frontEnd_exam.dropna(inplace=True)
df_frontEnd_exam

   UNISTRA card\rNo.       Surname Name   CC3
1           22423021      Abbasli Fidan  12.5
2           22423178    Abbasli Ismayil  13.1
3           22423324    Abbaszada Tunar  10.1
4           22422983  Abdurahmanov Amir     0
5           22423198   Abishov Mahammad   8.9
..               ...                ...   ...
24          22423199  Taghiyeva Mahsati  11.3
25          22423337       Valiyev Zaur  13.7
26          22423230   Yusibzada Narmin  16.1
27          22423304     Yusubov Telman  10.7
28          22423244    Zahidova Nazrin   8.9

[62 rows x 3 columns]

In [67]:
df_frontEnd_exam.count()

UNISTRA card\rNo.    62
Surname Name         62
CC3                  62
dtype: int64

In [68]:
df.count()

ID                  62
French Midterm 1    62
French Final        62
French Oral         62
CSPC midterm        62
CSPC Final          62
CSPC PW             62
DSA total           61
Math midterm        62
AOM midterm         87
AOM final           61
Thermodynamics      60
Point Mechanics     86
dtype: int64

In [69]:
#df

In [70]:
df_frontEnd_exam.columns = ['ID', 'Surname Name', 'FrontEnd Final']
df_frontEnd_exam

          ID       Surname Name FrontEnd Final
1   22423021      Abbasli Fidan           12.5
2   22423178    Abbasli Ismayil           13.1
3   22423324    Abbaszada Tunar           10.1
4   22422983  Abdurahmanov Amir              0
5   22423198   Abishov Mahammad            8.9
..       ...                ...            ...
24  22423199  Taghiyeva Mahsati           11.3
25  22423337       Valiyev Zaur           13.7
26  22423230   Yusibzada Narmin           16.1
27  22423304     Yusubov Telman           10.7
28  22423244    Zahidova Nazrin            8.9

[62 rows x 3 columns]

In [71]:
df['ID'] = df['ID'].astype(str).str.strip()
df_frontEnd_exam['ID'] = df_frontEnd_exam['ID'].astype(str).str.strip()

In [72]:
print(len(df['ID'].unique()))                # сколько уникальных ID в df
print(len(df_frontEnd_exam['ID'].unique()))  # сколько уникальных ID во втором
print(len(set(df['ID']) & set(df_frontEnd_exam['ID'])))  # пересечение

63
62
62

In [73]:
df_experiment = df_experiment = pd.merge(df, df_frontEnd_exam, on="ID")

In [74]:
df_experiment.count()
df = df_experiment

In [75]:
#df_frontEnd_exam

In [76]:
#df['ID'] = df['ID'].astype(int)
#df_frontEnd_exam['ID'] = df_frontEnd_exam['ID'].astype(int)

In [77]:
#print(df['ID'].dtype, df_frontEnd_exam['ID'].dtype)  # типы данных
#print(len(df), len(df_frontEnd_exam))                # размеры до
#merged = pd.merge(df, df_frontEnd_exam, on="ID", how="inner")
#print(len(merged))                                   # размер после

In [78]:
#df = pd.merge(df, df_frontEnd_exam, on="ID")
#df

In [79]:
#df.count()

In [80]:
#df = df[new_order]

## Front End Class Participation

In [81]:
classpart = tabula.read_pdf('grades/frontend_class.pdf', pages='all')

In [82]:
classpart

[    studentID  TPEval012 /8  TPN0 /9  TPN1 /9  TPN2 /11  TPN3 /8  TPN5 /11  \
 0    22423021             5      6.1      3.2       8.0      2.5       7.0
 1    22423178             8      8.5      7.7       9.1      6.3      10.7
 2    22423324             5      8.8      9.0       9.9      8.0      10.7
 3    22422983             2      NaN      8.7       NaN      NaN      10.7
 4    22423198             3      NaN      NaN       NaN      5.6       NaN
 5    22423293             5      8.6      4.1      10.4      6.6      10.9
 6    22423258             1      NaN      NaN       NaN      NaN       9.6
 7    22423161             5      6.4      6.7       9.2      6.6      10.4
 8    22423200             8      6.4      8.1       9.4      8.0       8.0
 9    22423307             6      7.7      8.1      10.3      6.8      10.9
 10   22423174             8      8.7      8.2       9.6      8.0      11.0
 11   22322620             0      NaN      NaN       NaN      NaN       NaN
 12   22422997             5      NaN      6.9       7.0      6.0       8.3
 13   22423162             8      8.8      8.3      10.6      6.6      10.6
 14   22423312             6      5.1      7.8       9.7      6.8      10.9
 15   22423242             7      8.4      8.2       9.4      8.0      10.6
 16   22423208             8      8.7      8.0       9.3      7.3       9.7
 17   22423213             8      8.5      8.1      10.2      6.8      11.0
 18   22423163             4      NaN      8.2      10.7      NaN      10.7
 19   22423185             5      NaN      NaN       NaN      6.8      10.6
 20   22423005             7      7.6      8.0       9.0      8.0       9.6
 21   22423010             4      8.6      8.0      11.0      6.8      10.9
 22   22423280             5      8.8      5.0       7.2      6.3      10.7
 23   22322607             4      NaN      7.9      10.0      8.0      10.7
 24   22423203             7      5.4      7.9       9.7      7.5      10.7
 25   22423001             6      8.1      6.0      10.3      6.3      10.9
 26   22423333             5      8.6      8.1       9.8      NaN       8.7
 27   22422990             5      8.3      7.5       NaN      7.5      11.0
 28   22423190             5      8.6      8.1      10.5      8.0      10.9
 29   22423301             5      8.7      7.0       9.8      6.8      10.9
 30   22423282             6      7.2      8.0       9.7      7.5       9.8
 31   22423192             6      7.3      7.5       8.9      6.6      10.9
 32   22423251             4      8.8      5.1      10.5      8.0      11.0
 33   22422989             5      8.6      8.1      10.1      7.3      10.9
 34   22423196             6      8.3      7.8       9.9      8.0      10.6
 35   22423334             5      6.8      4.8       9.9      7.8       7.7
 36   22423318             5      8.4      7.8      10.6      8.0      11.0
 37   22422993             5      7.3      6.8      10.0      6.3       9.9
 38   22422979             3      5.5      4.9       NaN      5.3       5.1

     quizN1N2 /4  quizN3 /4  quizN4 /4  quizN5 /4  quizN6 /4  quizN7N8 /4  \
 0           2.2        1.6        NaN        NaN        NaN          3.2
 1           2.0        2.6        3.1        3.2        3.6          3.5
 2           3.6        2.3        3.3        2.8        4.2          3.7
 3           NaN        NaN        NaN        NaN        NaN          NaN
 4           0.7        1.9        1.9        1.7        0.9          3.0
 5           2.9        1.7        NaN        NaN        4.0          2.9
 6           NaN        2.7        NaN        NaN        2.9          2.9
 7           3.5        3.9        2.7        2.8        4.9          3.9
 8           3.4        1.9        2.0        3.3        3.2          2.6
 9           1.5        2.6        NaN        3.1        4.3          2.0
 10          2.5        3.4        3.0        2.4        4.6          3.1
 11          NaN        NaN        NaN        NaN        NaN          NaN
 12          2.7        2.9        2.9        NaN        3.4          NaN
 13          3.0        2.5        2.8        2.9        4.0          3.0
 14          3.8        2.9        3.3        2.7        3.6          3.3
 15          4.0        2.5        3.1        3.3        3.3          3.3
 16          2.7        2.5        2.7        3.2        2.3          2.1
 17          1.1        3.3        3.4        3.8        4.4          2.4
 18          2.2        1.2        2.1        3.2        3.5          3.1
 19          3.0        2.6        NaN        NaN        4.5          2.7
 20          1.8        0.5        2.7        2.2        3.3          2.6
 21          2.5        1.6        3.1        NaN        NaN          2.8
 22          2.3        NaN        NaN        2.2        4.2          1.7
 23          NaN        3.5        3.0        3.6        4.2          3.3
 24          3.4        1.5        2.5        2.4        3.8          1.8
 25          2.7        1.6        3.0        2.7        3.4          NaN
 26          3.6        3.9        3.3        3.4        3.6          2.6
 27          2.3        2.9        3.1        2.5        3.5          2.5
 28          3.4        3.5        3.7        2.4        4.9          4.0
 29          2.8        3.7        3.5        2.7        4.2          3.4
 30          2.9        2.7        3.1        3.7        4.1          2.8
 31          3.5        2.5        2.8        2.3        3.2          2.4
 32          2.1        3.9        3.1        2.9        4.2          2.5
 33          2.8        3.0        2.6        3.5        4.6          3.3
 34          2.0        1.9        2.5        3.5        4.5          2.8
 35          3.1        3.1        3.2        3.3        4.3          3.4
 36          3.9        3.9        3.8        3.7        5.0          4.0
 37          3.1        1.7        2.1        3.6        3.5          NaN
 38          2.5        3.0        2.7        NaN        4.8          2.9

     Total / 80  Total /20
 0         38.8        9.7
 1         68.3       17.1
 2         71.3       17.8
 3         21.4        5.4
 4         18.7        4.7
 5         57.1       14.3
 6         19.1        4.8
 7         66.0       16.5
 8         64.3       16.1
 9         63.3       15.8
 10        72.5       18.1
 11         NaN        NaN
 12        45.1       11.3
 13        71.1       17.8
 14        65.9       16.5
 15        71.1       17.8
 16        66.5       16.6
 17        71.0       17.8
 18        48.9       12.2
 19        35.2        8.8
 20        62.3       15.6
 21        59.3       14.8
 22        53.4       13.4
 23        58.2       14.6
 24        63.6       15.9
 25        61.0       15.3
 26        60.6       15.2
 27        56.1       14.0
 28        73.0       18.3
 29        68.5       17.1
 30        67.5       16.9
 31        63.9       16.0
 32        66.1       16.5
 33        69.8       17.5
 34        67.8       17.0
 35        62.4       15.6
 36        75.1       18.8
 37        59.3       14.8
 38        39.7        9.9  ,
     22423023  6    8  7.8  10.5  6.8  10.9  3.4  3.4.1    3  3.6  4.5  \
 0   22423157  6  7.7  6.5   9.0  5.1  10.9  2.4    2.0  1.9  2.4  3.5
 1   22422999  4  6.9  7.1   9.5  5.9   7.8  3.1    3.4  2.5  2.8  3.5
 2   22423156  7  NaN  5.9   5.2  6.3  11.0  3.8    1.6  2.8  3.6  4.6
 3   22425334  8  5.2  8.0  10.5  8.0  11.0  3.3    3.6  3.9  2.2  4.9
 4   22422996  8  7.9  7.5   9.8  7.5   8.9  2.7    3.1  1.9  3.2  4.0
 5   22423182  5  7.2  5.7   7.4  5.9   7.8  3.1    3.0  3.3  NaN  4.4
 6   22423260  4  8.5  8.1  10.0  6.8  10.9  2.5    2.8  NaN  2.0  3.4
 7   22423169  6  5.4  5.5   8.6  6.8  10.3  3.5    3.3  1.9  3.5  3.2
 8   22423257  5  8.8  8.1  10.0  6.6  10.9  0.9    NaN  1.7  2.4  4.4
 9   22322638  2  NaN  6.4   9.3  8.0  10.4  3.0    3.7  3.9  3.3  4.4
 10  22423252  6  7.3  6.5   9.1  7.5  10.9  3.0    2.2  3.1  2.3  3.3
 11  22423234  8  8.8  7.0   8.5  7.3   8.2  3.7    3.3  1.4  3.1  4.5
 12  22422986  7  8.8  4.7   3.9  4.1   3.9  1.6    3.6  NaN  3.1  4.2
 13  22423254  6  7.7  7.9  10.2  8.0  11.0  3.7    2.5  3.8  3.8  3.6
 14  22423295  2  8.6  6.9   8.6  NaN   9.3  2.9    2.5  NaN  1.7  3.1
 15  22423233  6  7.4  7.5  10.1  6.8  10.7  2.5    3.3  3.4  2.2  4.3
 16  22423238  5  NaN  7.3  10.5  8.0  10.9  3.0    1.8  2.1  3.2  3.7
 17  22423199  7  7.8  7.0   9.0  7.8   9.9  3.2    3.4  3.4  2.5  4.1
 18  22423337  6  9.0  8.0   9.7  7.3  11.0  2.5    3.9  3.6  2.1  4.2
 19  22423230  6  NaN  8.1   9.4  NaN   8.5  2.6    0.9  2.2  NaN  1.7
 20  22423304  6  7.3  6.7  10.7  6.8  10.4  3.3    3.8  3.4  2.9  4.3
 21  22423244  6  7.9  7.7   7.2  6.8  10.9  3.3    2.9  3.6  3.2  3.8

     Unnamed: 0  67.9    17
 0          1.2  58.6  14.7
 1          3.3  59.8  15.0
 2          3.6  55.4  13.9
 3          3.7  72.3  18.1
 4          3.2  67.7  16.9
 5          2.4  55.2  13.8
 6          NaN  59.0  14.8
 7          2.9  60.9  15.2
 8          2.2  61.0  15.3
 9          2.6  57.0  14.3
 10         2.7  63.9  16.0
 11         2.9  66.7  16.7
 12         3.2  48.1  12.0
 13         4.0  72.2  18.1
 14         2.6  48.2  12.1
 15         2.9  67.1  16.8
 16         2.7  58.2  14.6
 17         1.9  67.0  16.8
 18         3.6  70.9  17.7
 19         1.5  40.9  10.2
 20         3.0  68.6  17.2
 21         3.1  66.4  16.6  ]

In [83]:
df_classpart = pd.DataFrame(classpart[0])
df_classpart1 = pd.DataFrame(classpart[1])

In [84]:
df_classpart1

,22423023,6,8,7.8,10.5,6.8,10.9,3.4,3.4.1,3,3.6,4.5,Unnamed: 0,67.9,17
0,22423157,6,7.7,6.5,9.0,5.1,10.9,2.4,2.0,1.9,2.4,3.5,1.2,58.6,14.7
1,22422999,4,6.9,7.1,9.5,5.9,7.8,3.1,3.4,2.5,2.8,3.5,3.3,59.8,15.0
2,22423156,7,NaN,5.9,5.2,6.3,11.0,3.8,1.6,2.8,3.6,4.6,3.6,55.4,13.9
3,22425334,8,5.2,8.0,10.5,8.0,11.0,3.3,3.6,3.9,2.2,4.9,3.7,72.3,18.1
4,22422996,8,7.9,7.5,9.8,7.5,8.9,2.7,3.1,1.9,3.2,4.0,3.2,67.7,16.9
5,22423182,5,7.2,5.7,7.4,5.9,7.8,3.1,3.0,3.3,NaN,4.4,2.4,55.2,13.8
6,22423260,4,8.5,8.1,10.0,6.8,10.9,2.5,2.8,NaN,2.0,3.4,NaN,59.0,14.8
7,22423169,6,5.4,5.5,8.6,6.8,10.3,3.5,3.3,1.9,3.5,3.2,2.9,60.9,15.2
8,22423257,5,8.8,8.1,10.0,6.6,10.9,0.9,NaN,1.7,2.4,4.4,2.2,61.0,15.3
9,22322638,2,NaN,6.4,9.3,8.0,10.4,3.0,3.7,3.9,3.3,4.4,2.6,57.0,14.3
10,22423252,6,7.3,6.5,9.1,7.5,10.9,3.0,2.2,3.1,2.3,3.3,2.7,63.9,16.0
11,22423234,8,8.8,7.0,8.5,7.3,8.2,3.7,3.3,1.4,3.1,4.5,2.9,66.7,16.7
12,22422986,7,8.8,4.7,3.9,4.1,3.9,1.6,3.6,NaN,3.1,4.2,3.2,48.1,12.0
13,22423254,6,7.7,7.9,10.2,8.0,11.0,3.7,2.5,3.8,3.8,3.6,4.0,72.2,18.1
14,22423295,2,8.6,6.9,8.6,NaN,9.3,2.9,2.5,NaN,1.7,3.1,2.6,48.2,12.1
15,22423233,6,7.4,7.5,10.1,6.8,10.7,2.5,3.3,3.4,2.2,4.3,2.9,67.1,16.8
16,22423238,5,NaN,7.3,10.5,8.0,10.9,3.0,1.8,2.1,3.2,3.7,2.7,58.2,14.6
17,22423199,7,7.8,7.0,9.0,7.8,9.9,3.2,3.4,3.4,2.5,4.1,1.9,67.0,16.8
18,22423337,6,9.0,8.0,9.7,7.3,11.0,2.5,3.9,3.6,2.1,4.2,3.6,70.9,17.7
19,22423230,6,NaN,8.1,9.4,NaN,8.5,2.6,0.9,2.2,NaN,1.7,1.5,40.9,10.2
20,22423304,6,7.3,6.7,10.7,6.8,10.4,3.3,3.8,3.4,2.9,4.3,3.0,68.6,17.2
21,22423244,6,7.9,7.7,7.2,6.8,10.9,3.3,2.9,3.6,3.2,3.8,3.1,66.4,16.6

In [85]:
df_classpart

,studentID,TPEval012 /8,TPN0 /9,TPN1 /9,TPN2 /11,TPN3 /8,TPN5 /11,quizN1N2 /4,quizN3 /4,quizN4 /4,quizN5 /4,quizN6 /4,quizN7N8 /4,Total / 80,Total /20
0,22423021,5,6.1,3.2,8.0,2.5,7.0,2.2,1.6,NaN,NaN,NaN,3.2,38.8,9.7
1,22423178,8,8.5,7.7,9.1,6.3,10.7,2.0,2.6,3.1,3.2,3.6,3.5,68.3,17.1
2,22423324,5,8.8,9.0,9.9,8.0,10.7,3.6,2.3,3.3,2.8,4.2,3.7,71.3,17.8
3,22422983,2,NaN,8.7,NaN,NaN,10.7,NaN,NaN,NaN,NaN,NaN,NaN,21.4,5.4
4,22423198,3,NaN,NaN,NaN,5.6,NaN,0.7,1.9,1.9,1.7,0.9,3.0,18.7,4.7
5,22423293,5,8.6,4.1,10.4,6.6,10.9,2.9,1.7,NaN,NaN,4.0,2.9,57.1,14.3
6,22423258,1,NaN,NaN,NaN,NaN,9.6,NaN,2.7,NaN,NaN,2.9,2.9,19.1,4.8
7,22423161,5,6.4,6.7,9.2,6.6,10.4,3.5,3.9,2.7,2.8,4.9,3.9,66.0,16.5
8,22423200,8,6.4,8.1,9.4,8.0,8.0,3.4,1.9,2.0,3.3,3.2,2.6,64.3,16.1
9,22423307,6,7.7,8.1,10.3,6.8,10.9,1.5,2.6,NaN,3.1,4.3,2.0,63.3,15.8
10,22423174,8,8.7,8.2,9.6,8.0,11.0,2.5,3.4,3.0,2.4,4.6,3.1,72.5,18.1
11,22322620,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,22422997,5,NaN,6.9,7.0,6.0,8.3,2.7,2.9,2.9,NaN,3.4,NaN,45.1,11.3
13,22423162,8,8.8,8.3,10.6,6.6,10.6,3.0,2.5,2.8,2.9,4.0,3.0,71.1,17.8
14,22423312,6,5.1,7.8,9.7,6.8,10.9,3.8,2.9,3.3,2.7,3.6,3.3,65.9,16.5
15,22423242,7,8.4,8.2,9.4,8.0,10.6,4.0,2.5,3.1,3.3,3.3,3.3,71.1,17.8
16,22423208,8,8.7,8.0,9.3,7.3,9.7,2.7,2.5,2.7,3.2,2.3,2.1,66.5,16.6
17,22423213,8,8.5,8.1,10.2,6.8,11.0,1.1,3.3,3.4,3.8,4.4,2.4,71.0,17.8
18,22423163,4,NaN,8.2,10.7,NaN,10.7,2.2,1.2,2.1,3.2,3.5,3.1,48.9,12.2
19,22423185,5,NaN,NaN,NaN,6.8,10.6,3.0,2.6,NaN,NaN,4.5,2.7,35.2,8.8
20,22423005,7,7.6,8.0,9.0,8.0,9.6,1.8,0.5,2.7,2.2,3.3,2.6,62.3,15.6
21,22423010,4,8.6,8.0,11.0,6.8,10.9,2.5,1.6,3.1,NaN,NaN,2.8,59.3,14.8
22,22423280,5,8.8,5.0,7.2,6.3,10.7,2.3,NaN,NaN,2.2,4.2,1.7,53.4,13.4
23,22322607,4,NaN,7.9,10.0,8.0,10.7,NaN,3.5,3.0,3.6,4.2,3.3,58.2,14.6
24,22423203,7,5.4,7.9,9.7,7.5,10.7,3.4,1.5,2.5,2.4,3.8,1.8,63.6,15.9
25,22423001,6,8.1,6.0,10.3,6.3,10.9,2.7,1.6,3.0,2.7,3.4,NaN,61.0,15.3
26,22423333,5,8.6,8.1,9.8,NaN,8.7,3.6,3.9,3.3,3.4,3.6,2.6,60.6,15.2
27,22422990,5,8.3,7.5,NaN,7.5,11.0,2.3,2.9,3.1,2.5,3.5,2.5,56.1,14.0
28,22423190,5,8.6,8.1,10.5,8.0,10.9,3.4,3.5,3.7,2.4,4.9,4.0,73.0,18.3
29,22423301,5,8.7,7.0,9.8,6.8,10.9,2.8,3.7,3.5,2.7,4.2,3.4,68.5,17.1
30,22423282,6,7.2,8.0,9.7,7.5,9.8,2.9,2.7,3.1,3.7,4.1,2.8,67.5,16.9
31,22423192,6,7.3,7.5,8.9,6.6,10.9,3.5,2.5,2.8,2.3,3.2,2.4,63.9,16.0
32,22423251,4,8.8,5.1,10.5,8.0,11.0,2.1,3.9,3.1,2.9,4.2,2.5,66.1,16.5
33,22422989,5,8.6,8.1,10.1,7.3,10.9,2.8,3.0,2.6,3.5,4.6,3.3,69.8,17.5
34,22423196,6,8.3,7.8,9.9,8.0,10.6,2.0,1.9,2.5,3.5,4.5,2.8,67.8,17.0
35,22423334,5,6.8,4.8,9.9,7.8,7.7,3.1,3.1,3.2,3.3,4.3,3.4,62.4,15.6
36,22423318,5,8.4,7.8,10.6,8.0,11.0,3.9,3.9,3.8,3.7,5.0,4.0,75.1,18.8
37,22422993,5,7.3,6.8,10.0,6.3,9.9,3.1,1.7,2.1,3.6,3.5,NaN,59.3,14.8
38,22422979,3,5.5,4.9,NaN,5.3,5.1,2.5,3.0,2.7,NaN,4.8,2.9,39.7,9.9

In [86]:
#datarow = df_classpart1.columns.to_series()
#datarow = pd.DataFrame(datarow)
#datarow = datarow.T
#datarow.columns = df_frontEnd_exam_part1.columns

#df_classpart1 = pd.concat([df_classpart, datarow])

df_classpart1

,22423023,6,8,7.8,10.5,6.8,10.9,3.4,3.4.1,3,3.6,4.5,Unnamed: 0,67.9,17
0,22423157,6,7.7,6.5,9.0,5.1,10.9,2.4,2.0,1.9,2.4,3.5,1.2,58.6,14.7
1,22422999,4,6.9,7.1,9.5,5.9,7.8,3.1,3.4,2.5,2.8,3.5,3.3,59.8,15.0
2,22423156,7,NaN,5.9,5.2,6.3,11.0,3.8,1.6,2.8,3.6,4.6,3.6,55.4,13.9
3,22425334,8,5.2,8.0,10.5,8.0,11.0,3.3,3.6,3.9,2.2,4.9,3.7,72.3,18.1
4,22422996,8,7.9,7.5,9.8,7.5,8.9,2.7,3.1,1.9,3.2,4.0,3.2,67.7,16.9
5,22423182,5,7.2,5.7,7.4,5.9,7.8,3.1,3.0,3.3,NaN,4.4,2.4,55.2,13.8
6,22423260,4,8.5,8.1,10.0,6.8,10.9,2.5,2.8,NaN,2.0,3.4,NaN,59.0,14.8
7,22423169,6,5.4,5.5,8.6,6.8,10.3,3.5,3.3,1.9,3.5,3.2,2.9,60.9,15.2
8,22423257,5,8.8,8.1,10.0,6.6,10.9,0.9,NaN,1.7,2.4,4.4,2.2,61.0,15.3
9,22322638,2,NaN,6.4,9.3,8.0,10.4,3.0,3.7,3.9,3.3,4.4,2.6,57.0,14.3
10,22423252,6,7.3,6.5,9.1,7.5,10.9,3.0,2.2,3.1,2.3,3.3,2.7,63.9,16.0
11,22423234,8,8.8,7.0,8.5,7.3,8.2,3.7,3.3,1.4,3.1,4.5,2.9,66.7,16.7
12,22422986,7,8.8,4.7,3.9,4.1,3.9,1.6,3.6,NaN,3.1,4.2,3.2,48.1,12.0
13,22423254,6,7.7,7.9,10.2,8.0,11.0,3.7,2.5,3.8,3.8,3.6,4.0,72.2,18.1
14,22423295,2,8.6,6.9,8.6,NaN,9.3,2.9,2.5,NaN,1.7,3.1,2.6,48.2,12.1
15,22423233,6,7.4,7.5,10.1,6.8,10.7,2.5,3.3,3.4,2.2,4.3,2.9,67.1,16.8
16,22423238,5,NaN,7.3,10.5,8.0,10.9,3.0,1.8,2.1,3.2,3.7,2.7,58.2,14.6
17,22423199,7,7.8,7.0,9.0,7.8,9.9,3.2,3.4,3.4,2.5,4.1,1.9,67.0,16.8
18,22423337,6,9.0,8.0,9.7,7.3,11.0,2.5,3.9,3.6,2.1,4.2,3.6,70.9,17.7
19,22423230,6,NaN,8.1,9.4,NaN,8.5,2.6,0.9,2.2,NaN,1.7,1.5,40.9,10.2
20,22423304,6,7.3,6.7,10.7,6.8,10.4,3.3,3.8,3.4,2.9,4.3,3.0,68.6,17.2
21,22423244,6,7.9,7.7,7.2,6.8,10.9,3.3,2.9,3.6,3.2,3.8,3.1,66.4,16.6

In [87]:
df_classpart.drop(df_classpart.columns[1:14], axis=1, inplace=True)

In [88]:
df_classpart1.drop(df_classpart1.columns[1:14], axis=1, inplace=True)

In [89]:
datarow = pd.Series(df_classpart1.columns)

In [90]:
datarow = datarow.to_frame().T
datarow.columns = df_classpart.columns
datarow

  studentID Total /20
0  22423023        17

In [91]:
df_classpart1.columns = df_classpart.columns
df_classpart1

    studentID  Total /20
0    22423157       14.7
1    22422999       15.0
2    22423156       13.9
3    22425334       18.1
4    22422996       16.9
5    22423182       13.8
6    22423260       14.8
7    22423169       15.2
8    22423257       15.3
9    22322638       14.3
10   22423252       16.0
11   22423234       16.7
12   22422986       12.0
13   22423254       18.1
14   22423295       12.1
15   22423233       16.8
16   22423238       14.6
17   22423199       16.8
18   22423337       17.7
19   22423230       10.2
20   22423304       17.2
21   22423244       16.6

In [92]:
df_classpart = pd.concat([df_classpart, datarow], ignore_index=True)
df_classpart

   studentID Total /20
0   22423021       9.7
1   22423178      17.1
2   22423324      17.8
3   22422983       5.4
4   22423198       4.7
5   22423293      14.3
6   22423258       4.8
7   22423161      16.5
8   22423200      16.1
9   22423307      15.8
10  22423174      18.1
11  22322620       NaN
12  22422997      11.3
13  22423162      17.8
14  22423312      16.5
15  22423242      17.8
16  22423208      16.6
17  22423213      17.8
18  22423163      12.2
19  22423185       8.8
20  22423005      15.6
21  22423010      14.8
22  22423280      13.4
23  22322607      14.6
24  22423203      15.9
25  22423001      15.3
26  22423333      15.2
27  22422990      14.0
28  22423190      18.3
29  22423301      17.1
30  22423282      16.9
31  22423192      16.0
32  22423251      16.5
33  22422989      17.5
34  22423196      17.0
35  22423334      15.6
36  22423318      18.8
37  22422993      14.8
38  22422979       9.9
39  22423023        17

In [93]:
df_classpart = pd.concat([df_classpart, df_classpart1])

In [94]:
df_classpart.rename(columns={'studentID':'ID', 'Total /20':'FrontEnd PW'}, inplace=True)
df_classpart

          ID FrontEnd PW
0   22423021         9.7
1   22423178        17.1
2   22423324        17.8
3   22422983         5.4
4   22423198         4.7
..       ...         ...
17  22423199        16.8
18  22423337        17.7
19  22423230        10.2
20  22423304        17.2
21  22423244        16.6

[62 rows x 2 columns]

In [95]:
df_classpart["ID"] = df_classpart["ID"].astype(str).str.strip()
df["ID"] = df["ID"].astype(str).str.strip()

In [96]:
df

,ID,French Midterm 1,French Final,French Oral,CSPC midterm,CSPC Final,CSPC PW,DSA total,Math midterm,AOM midterm,AOM final,Thermodynamics,Point Mechanics,Surname Name,FrontEnd Final
0,22423021,17,18.5,"17,5",18.667,10.8355,15.769231,12,"3,50",9.615385,4.81,8.75,4.32,Abbasli Fidan,12.5
1,22423178,13,15.5,15,14.001,12.835,18.076923,16.1,"5,25",7.884615,12.23,14.25,11.4,Abbasli Ismayil,13.1
2,22423324,17,15,"17,75",18.667,12.1685,19.230769,15.5,"12,75",14.807692,17.67,11,12.6,Abbaszada Tunar,10.1
3,22422983,19,11.5,14,12.002,7.002,15.897436,16.2,"2,50",8.5,4.07,0.5,ab,Abdurahmanov Amir,0
4,22423198,15,13.5,16,12.335,7.8345,15.769231,12.3,"4,75",2.884615,2.22,5,3.84,Abishov Mahammad,8.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,22423199,18,18,17,14.668,12.6685,11.645833,14.8,"16,25",13.46,10.56,10.55,2.34,Taghiyeva Mahsati,11.3
58,22423337,"10,5",16,12.5,14.668,14.0015,11.270833,12.3,"8,75",12.31,10,12.25,1.2,Valiyev Zaur,13.7
59,22423230,16,20,19.5,16.334,10.002,8.75,14.3,"12,50",12.31,3.7,5.75,4.44,Yusibzada Narmin,16.1
60,22423304,"18,5",17,18,14.668,13.168,13.020833,12.8,"11,75",7.69,6.06,8.8,0,Yusubov Telman,10.7
61,22423244,"18,5",20,16.5,14.668,11.1685,10.729167,11.6,"7,00",10.77,8.15,4,4.92,Zahidova Nazrin,8.9

In [97]:
df = pd.merge(df, df_classpart, on='ID')

In [98]:
df

,ID,French Midterm 1,French Final,French Oral,CSPC midterm,CSPC Final,CSPC PW,DSA total,Math midterm,AOM midterm,AOM final,Thermodynamics,Point Mechanics,Surname Name,FrontEnd Final,FrontEnd PW
0,22423021,17,18.5,"17,5",18.667,10.8355,15.769231,12,"3,50",9.615385,4.81,8.75,4.32,Abbasli Fidan,12.5,9.7
1,22423178,13,15.5,15,14.001,12.835,18.076923,16.1,"5,25",7.884615,12.23,14.25,11.4,Abbasli Ismayil,13.1,17.1
2,22423324,17,15,"17,75",18.667,12.1685,19.230769,15.5,"12,75",14.807692,17.67,11,12.6,Abbaszada Tunar,10.1,17.8
3,22422983,19,11.5,14,12.002,7.002,15.897436,16.2,"2,50",8.5,4.07,0.5,ab,Abdurahmanov Amir,0,5.4
4,22423198,15,13.5,16,12.335,7.8345,15.769231,12.3,"4,75",2.884615,2.22,5,3.84,Abishov Mahammad,8.9,4.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,22423199,18,18,17,14.668,12.6685,11.645833,14.8,"16,25",13.46,10.56,10.55,2.34,Taghiyeva Mahsati,11.3,16.8
58,22423337,"10,5",16,12.5,14.668,14.0015,11.270833,12.3,"8,75",12.31,10,12.25,1.2,Valiyev Zaur,13.7,17.7
59,22423230,16,20,19.5,16.334,10.002,8.75,14.3,"12,50",12.31,3.7,5.75,4.44,Yusibzada Narmin,16.1,10.2
60,22423304,"18,5",17,18,14.668,13.168,13.020833,12.8,"11,75",7.69,6.06,8.8,0,Yusubov Telman,10.7,17.2
61,22423244,"18,5",20,16.5,14.668,11.1685,10.729167,11.6,"7,00",10.77,8.15,4,4.92,Zahidova Nazrin,8.9,16.6

## FrontEnd Homework Project

In [99]:
project = tabula.read_pdf('grades/FrontEndProject.pdf', pages='all')

In [100]:
df_frontend_project = pd.DataFrame(project[0])
df_frontend_project1 = pd.DataFrame(project[1])

In [101]:
df_frontend_project

,N°Order,lastname,firstname,Step1 /20\r25%,Step2 /20\r5%,/20\r60%,HWP Exam /20\r10%,Total HWP\rCC2 /20
0,1,Abbasli,Fidan,10.7,0,13.9,4,11.4
1,2,Abbasli,Ismayil,13.8,20,16.0,16,15.7
2,3,Abbaszada,Tunar,0.0,20,17.4,4,11.8
3,4,Abdurahman,Avmir,17.9,20,10.2,0,11.6
4,5,Abishov,Mahammad,0.0,0,NaN,4,0.4
5,6,Aghamaliyev,Said,17.9,20,16.9,10,16.6
6,7,Ahmadzada,Raul,0.0,20,13.2,4,9.3
7,8,Akhundova,Gunay,6.9,20,17.5,4,13.6
8,9,Akhundova,Maryam,18.3,20,17.2,10,16.9
9,10,Alasgarov,Teymur,16.9,20,16.6,10,16.2
10,11,Algayeva,Ilaha,15.5,20,17.1,12,16.3
11,12,Ali?pashayev,Ravan,0.0,0,NaN,0,NaN
12,13,Aliyev,Elnur,0.0,0,NaN,0,NaN
13,14,Aliyev,Hakim,17.9,20,18.1,10,17.3
14,15,Alizada,Tofig,12.4,10,14.9,12,13.7
15,16,Asadli,Nasrin,15.9,20,16.4,16,16.4
16,17,Atlukhanov,Murad,13.8,20,15.2,10,14.6
17,18,Azizov,Nadir,15.5,20,15.8,14,15.8
18,19,Balayev,Huseyn,14.5,20,16.5,10,15.5
19,20,Bayramli,Javid,6.2,20,16.8,6,13.2
20,21,Budagov,Farhad,16.6,20,17.7,8,16.6
21,22,Burjaliyev,Farhad,17.9,20,16.3,2,15.5
22,23,Garibov,Sabuhi,11.7,20,15.2,12,14.2
23,24,Gasimov,Murad,14.1,20,13.6,4,13.1
24,25,Guliyev,Mikayil,15.5,20,15.7,10,15.3
25,26,Gulmammad,Fvamil,12.1,20,17.4,8,15.3
26,27,Haji-Nabili,Tural,14.8,20,14.8,14,15.0
27,28,Hajiyev,Bahruz,13.8,20,16.3,0,14.2
28,29,Hasanli,Kamil,2.8,20,16.9,8,12.6
29,30,Hasanova,Tamara,16.6,20,16.6,12,16.3
30,31,Hasratli,Said,11.4,20,16.1,4,13.9
31,32,Huseynli,Kamran,14.1,20,16.5,12,15.6
32,33,Ilyasli,Nilufar,16.2,20,15.4,8,15.1
33,34,Jafarova,Aziza,8.3,20,15.7,10,13.5
34,35,Javadzade,Mahammad,15.5,20,16.3,14,16.1
35,36,Khalafli,Yusif,15.5,20,16.9,10,16.0
36,37,Khankishiza,eTunar,9.3,20,14.9,8,13.1
37,38,Kuchinskiy,Daniil,15.9,20,15.1,0,14.0
38,39,Majidzade,Ali,16.2,20,17.7,14,17.1
39,40,Mammadli,Fidan,4.5,20,16.0,8,12.5
40,41,Mammadli,Gulzar,9.7,20,15.6,6,13.4
41,42,Mammadov,Elsel,10.0,20,11.8,4,11.0
42,43,Mammadova,Fatma,18.6,20,12.6,6,13.8
43,44,Mohammad,Iaskair,10.0,20,17.7,4,14.5
44,45,Mutallimov,Eldar,9.7,20,15.4,12,13.9
45,46,Najafzade,Jansu,15.5,20,14.8,8,14.6

In [102]:
df_frontend_project1

       47 Rahimbayov     Riad     0    20  15.5     6  10.9
0      48    Rahimli    Igbal   9.0  20.0  14.6  12.0  13.2
1      49    Rahimov    Rasul   0.0  20.0  17.5  10.0  12.5
2      50   Rashidli    Yusif   1.4  20.0  12.5   2.0   9.1
3      51      Rzali    Nuray  15.9  20.0  15.2   6.0  14.7
4      52    Rzayeva  Narmina  15.5  20.0  18.2   8.0  16.6
5      53    Safarov    Ayhan  13.8   0.0  13.8   8.0  12.5
6      54    Salahov   Parvin  15.9  20.0  16.6  10.0  15.9
7      55    Salahov     Sami   4.5   0.0  16.1   2.0  11.0
8      56    Seyidli   Narmin  14.5  20.0  15.2   4.0  14.1
9      57  Sharifova  Narmina  13.4  20.0  15.0  16.0  15.0
10     58  Taghiyeva  Mahsati  15.2  10.0  14.3   2.0  13.1
11     59    Valiyev     Zaur  13.1  10.0  15.3   6.0  13.6
12     60  Yusibzada   Narmin   7.2  10.0  15.5   8.0  12.4
13     61    Yusubov   Telman  16.6   0.0  13.2   2.0  12.3
14     62   Zahidova   Nazrin  16.2   0.0  17.0   4.0  14.7
15    MAX       17.3      NaN   NaN   NaN   NaN   NaN   NaN
16    AVG       13.9      NaN   NaN   NaN   NaN   NaN   NaN
17  STDEV        2.6      NaN   NaN   NaN   NaN   NaN   NaN

We already have the dataframe with names, surnames and corresponding IDs — `df`.

We can preprocess the project data and then merge the datafreames on `Surname Name` columns.

In [103]:
# We should preprocess the `df_frontend_project` and `df_frontend_project1` to one table. We can do so as we did with
# previous dataframes (see: front-end final and front-end pw)
datarow = df_frontend_project1.columns.to_frame().T
datarow.columns = df_frontend_project.columns

df_frontend_project = pd.concat([df_frontend_project, datarow], ignore_index=True)
df_frontend_project1.columns = df_frontend_project.columns

df_frontend_project = pd.concat([df_frontend_project, df_frontend_project1])
# now we have table with all grades of final project. The problem is missing IDs and some problems with names of students (e.g. Alipashayev Ravan)
# now it will be preprocessed

In [104]:
df_frontend_project.drop(columns=['N°Order', 'Step1 /20\r25%', 'Step2 /20\r5%', '/20\r60%', 'HWP Exam /20\r10%'], inplace=True)
df_frontend_project.reset_index(drop=True, inplace=True)


df_frontend_project.columns = ['lastname', 'firstname', 'FrontEnd Project']

In [105]:
# now let us add new column what will store both surname and name as one column
df_frontend_project['Surname Name'] = df['Surname Name'] # the order is always alphabetic so we can do this
# and we can get rid of `lastname` and `firstname` columns
df_frontend_project.drop(columns=['lastname', 'firstname'], inplace=True)

In [106]:
df_frontend_project

   FrontEnd Project       Surname Name
0              11.4      Abbasli Fidan
1              15.7    Abbasli Ismayil
2              11.8    Abbaszada Tunar
3              11.6  Abdurahmanov Amir
4               0.4   Abishov Mahammad
..              ...                ...
60             12.3     Yusubov Telman
61             14.7    Zahidova Nazrin
62              NaN                NaN
63              NaN                NaN
64              NaN                NaN

[65 rows x 2 columns]

In [107]:
df = pd.merge(df, df_frontend_project, on='Surname Name')

In [108]:
df

,ID,French Midterm 1,French Final,French Oral,CSPC midterm,CSPC Final,CSPC PW,DSA total,Math midterm,AOM midterm,AOM final,Thermodynamics,Point Mechanics,Surname Name,FrontEnd Final,FrontEnd PW,FrontEnd Project
0,22423021,17,18.5,"17,5",18.667,10.8355,15.769231,12,"3,50",9.615385,4.81,8.75,4.32,Abbasli Fidan,12.5,9.7,11.4
1,22423178,13,15.5,15,14.001,12.835,18.076923,16.1,"5,25",7.884615,12.23,14.25,11.4,Abbasli Ismayil,13.1,17.1,15.7
2,22423324,17,15,"17,75",18.667,12.1685,19.230769,15.5,"12,75",14.807692,17.67,11,12.6,Abbaszada Tunar,10.1,17.8,11.8
3,22422983,19,11.5,14,12.002,7.002,15.897436,16.2,"2,50",8.5,4.07,0.5,ab,Abdurahmanov Amir,0,5.4,11.6
4,22423198,15,13.5,16,12.335,7.8345,15.769231,12.3,"4,75",2.884615,2.22,5,3.84,Abishov Mahammad,8.9,4.7,0.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,22423199,18,18,17,14.668,12.6685,11.645833,14.8,"16,25",13.46,10.56,10.55,2.34,Taghiyeva Mahsati,11.3,16.8,13.1
58,22423337,"10,5",16,12.5,14.668,14.0015,11.270833,12.3,"8,75",12.31,10,12.25,1.2,Valiyev Zaur,13.7,17.7,13.6
59,22423230,16,20,19.5,16.334,10.002,8.75,14.3,"12,50",12.31,3.7,5.75,4.44,Yusibzada Narmin,16.1,10.2,12.4
60,22423304,"18,5",17,18,14.668,13.168,13.020833,12.8,"11,75",7.69,6.06,8.8,0,Yusubov Telman,10.7,17.2,12.3
61,22423244,"18,5",20,16.5,14.668,11.1685,10.729167,11.6,"7,00",10.77,8.15,4,4.92,Zahidova Nazrin,8.9,16.6,14.7

## Fluid Mechanics

In [109]:
df_fluid = pd.read_excel("grades/L1 - Fluid Mechanics grades.xlsx", sheet_name="CS")

In [110]:
df_fluid

,Unnamed: 0,Academic Year 2025/2026,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Computer science L1,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Semester 1,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
65,27,22423199,7,NaN,NaN,NaN
66,28,22423337,6,NaN,NaN,NaN
67,29,22423230,0,NaN,NaN,NaN
68,30,22423304,0.5,NaN,NaN,NaN
69,31,22423244,5,NaN,NaN,NaN

In [111]:
df_fluid.drop([0, 1, 2, 3, 4, 5, 6],inplace=True)
df_fluid.drop(["Unnamed: 0", "Unnamed: 3", "Unnamed: 4", "Unnamed: 5"], axis=1, inplace=True)
df_fluid.rename(columns={'Academic Year 2025/2026' : 'ID', 'Unnamed: 2' : 'Fluid Mechanics'}, inplace=True)
df_fluid

          ID Fluid Mechanics
7   22423021             4.5
8   22423178               9
9   22423324            12.5
10  22422983             NaN
11  22423198             6.5
..       ...             ...
65  22423199               7
66  22423337               6
67  22423230               0
68  22423304             0.5
69  22423244               5

[63 rows x 2 columns]

In [112]:
df

,ID,French Midterm 1,French Final,French Oral,CSPC midterm,CSPC Final,CSPC PW,DSA total,Math midterm,AOM midterm,AOM final,Thermodynamics,Point Mechanics,Surname Name,FrontEnd Final,FrontEnd PW,FrontEnd Project
0,22423021,17,18.5,"17,5",18.667,10.8355,15.769231,12,"3,50",9.615385,4.81,8.75,4.32,Abbasli Fidan,12.5,9.7,11.4
1,22423178,13,15.5,15,14.001,12.835,18.076923,16.1,"5,25",7.884615,12.23,14.25,11.4,Abbasli Ismayil,13.1,17.1,15.7
2,22423324,17,15,"17,75",18.667,12.1685,19.230769,15.5,"12,75",14.807692,17.67,11,12.6,Abbaszada Tunar,10.1,17.8,11.8
3,22422983,19,11.5,14,12.002,7.002,15.897436,16.2,"2,50",8.5,4.07,0.5,ab,Abdurahmanov Amir,0,5.4,11.6
4,22423198,15,13.5,16,12.335,7.8345,15.769231,12.3,"4,75",2.884615,2.22,5,3.84,Abishov Mahammad,8.9,4.7,0.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,22423199,18,18,17,14.668,12.6685,11.645833,14.8,"16,25",13.46,10.56,10.55,2.34,Taghiyeva Mahsati,11.3,16.8,13.1
58,22423337,"10,5",16,12.5,14.668,14.0015,11.270833,12.3,"8,75",12.31,10,12.25,1.2,Valiyev Zaur,13.7,17.7,13.6
59,22423230,16,20,19.5,16.334,10.002,8.75,14.3,"12,50",12.31,3.7,5.75,4.44,Yusibzada Narmin,16.1,10.2,12.4
60,22423304,"18,5",17,18,14.668,13.168,13.020833,12.8,"11,75",7.69,6.06,8.8,0,Yusubov Telman,10.7,17.2,12.3
61,22423244,"18,5",20,16.5,14.668,11.1685,10.729167,11.6,"7,00",10.77,8.15,4,4.92,Zahidova Nazrin,8.9,16.6,14.7

In [113]:
df_fluid['ID'] = df_fluid['ID'].astype(str).str.strip()

In [114]:
df = pd.merge(df, df_fluid, on="ID")
df

,ID,French Midterm 1,French Final,French Oral,CSPC midterm,CSPC Final,CSPC PW,DSA total,Math midterm,AOM midterm,AOM final,Thermodynamics,Point Mechanics,Surname Name,FrontEnd Final,FrontEnd PW,FrontEnd Project,Fluid Mechanics
0,22423021,17,18.5,"17,5",18.667,10.8355,15.769231,12,"3,50",9.615385,4.81,8.75,4.32,Abbasli Fidan,12.5,9.7,11.4,4.5
1,22423178,13,15.5,15,14.001,12.835,18.076923,16.1,"5,25",7.884615,12.23,14.25,11.4,Abbasli Ismayil,13.1,17.1,15.7,9
2,22423324,17,15,"17,75",18.667,12.1685,19.230769,15.5,"12,75",14.807692,17.67,11,12.6,Abbaszada Tunar,10.1,17.8,11.8,12.5
3,22422983,19,11.5,14,12.002,7.002,15.897436,16.2,"2,50",8.5,4.07,0.5,ab,Abdurahmanov Amir,0,5.4,11.6,NaN
4,22423198,15,13.5,16,12.335,7.8345,15.769231,12.3,"4,75",2.884615,2.22,5,3.84,Abishov Mahammad,8.9,4.7,0.4,6.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,22423199,18,18,17,14.668,12.6685,11.645833,14.8,"16,25",13.46,10.56,10.55,2.34,Taghiyeva Mahsati,11.3,16.8,13.1,7
58,22423337,"10,5",16,12.5,14.668,14.0015,11.270833,12.3,"8,75",12.31,10,12.25,1.2,Valiyev Zaur,13.7,17.7,13.6,6
59,22423230,16,20,19.5,16.334,10.002,8.75,14.3,"12,50",12.31,3.7,5.75,4.44,Yusibzada Narmin,16.1,10.2,12.4,0
60,22423304,"18,5",17,18,14.668,13.168,13.020833,12.8,"11,75",7.69,6.06,8.8,0,Yusubov Telman,10.7,17.2,12.3,0.5
61,22423244,"18,5",20,16.5,14.668,11.1685,10.729167,11.6,"7,00",10.77,8.15,4,4.92,Zahidova Nazrin,8.9,16.6,14.7,5

## Math Participation

In [115]:
df_mpart = pd.read_excel("grades/L1-024 MATH Grade sheet participation.xlsx", sheet_name="CS")
df_mpart

   Unnamed: 0 Academic Year 2025/2026 Unnamed: 2 Unnamed: 3 Unnamed: 4
0         NaN                     NaN        NaN        NaN        NaN
1         NaN     Computer science L1        NaN        NaN        NaN
2         NaN                     NaN        NaN        NaN        NaN
3         NaN              Semester 1        NaN        NaN        NaN
4         NaN                     NaN        NaN        NaN        NaN
..        ...                     ...        ...        ...        ...
65         27                22423199         19        NaN        NaN
66         28                22423337         18        NaN        NaN
67         29                22423230         15        NaN        NaN
68         30                22423304         20        NaN        NaN
69         31                22423244         18        NaN        NaN

[70 rows x 5 columns]

In [116]:
df_mpart.drop([0, 1, 2, 3, 4, 5, 6],inplace=True)
df_mpart.drop(["Unnamed: 0", "Unnamed: 3", "Unnamed: 4"], axis=1, inplace=True)
df_mpart.rename(columns={'Academic Year 2025/2026' : 'ID', 'Unnamed: 2' : 'Math Participation'}, inplace=True)
df_mpart

          ID Math Participation
7   22423021                 13
8   22423178                 17
9   22423324                 17
10  22422983                 10
11  22423198                 13
..       ...                ...
65  22423199                 19
66  22423337                 18
67  22423230                 15
68  22423304                 20
69  22423244                 18

[63 rows x 2 columns]

In [117]:
df_mpart['ID'] = df_mpart['ID'].astype(str).str.strip()

In [118]:
df = pd.merge(df, df_mpart, on="ID")
df.count()

ID                    62
French Midterm 1      62
French Final          62
French Oral           62
CSPC midterm          62
CSPC Final            62
CSPC PW               62
DSA total             61
Math midterm          62
AOM midterm           59
AOM final             61
Thermodynamics        60
Point Mechanics       62
Surname Name          62
FrontEnd Final        62
FrontEnd PW           61
FrontEnd Project      60
Fluid Mechanics       61
Math Participation    62
dtype: int64

## Chem Labs

In [119]:
df_lab = pd.read_excel("grades/L1-024 Chemistry Lab grades.xlsx", sheet_name="CS", skiprows=[38, 39])
df_lab

,Unnamed: 0,Academic Year 2025/2026,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Computer science L1,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Semester 1,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
65,28,22423337,15,17,13,14.5
66,29,22423230,11,9,12,11
67,30,22423304,16,17,13,14.75
68,31,22423244,15,17,9,12.5
69,NaN,NaN,15.612903,16.129032,12.322581,14.096774

In [120]:
df_lab.drop([0, 1, 2, 3, 4, 5, 6],inplace=True)

In [121]:
df_lab

,Unnamed: 0,Academic Year 2025/2026,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
7,1,22423021,16,15,14.5,15
8,2,22423178,14,17,16,15.75
9,3,22423324,16,15,14.5,15
10,4,22422983,12,15,13,13.25
11,5,22423198,13,NaN,11,8.75
...,...,...,...,...,...,...
65,28,22423337,15,17,13,14.5
66,29,22423230,11,9,12,11
67,30,22423304,16,17,13,14.75
68,31,22423244,15,17,9,12.5
69,NaN,NaN,15.612903,16.129032,12.322581,14.096774

In [122]:
df_lab.drop(["Unnamed: 0", "Unnamed: 2", "Unnamed: 3", "Unnamed: 4"], axis=1, inplace=True)
df_lab.rename(columns={'Academic Year 2025/2026' : 'ID', 'Unnamed: 5' : 'Chem Labs'}, inplace=True)
df_lab

          ID  Chem Labs
7   22423021         15
8   22423178      15.75
9   22423324         15
10  22422983      13.25
11  22423198       8.75
..       ...        ...
65  22423337       14.5
66  22423230         11
67  22423304      14.75
68  22423244       12.5
69       NaN  14.096774

[63 rows x 2 columns]

In [123]:
df_lab['ID'] = df_lab['ID'].astype(str).str.strip()

In [124]:
df = pd.merge(df, df_lab, on="ID")
df

,ID,French Midterm 1,French Final,French Oral,CSPC midterm,CSPC Final,CSPC PW,DSA total,Math midterm,AOM midterm,AOM final,Thermodynamics,Point Mechanics,Surname Name,FrontEnd Final,FrontEnd PW,FrontEnd Project,Fluid Mechanics,Math Participation,Chem Labs
0,22423021,17,18.5,"17,5",18.667,10.8355,15.769231,12,"3,50",9.615385,4.81,8.75,4.32,Abbasli Fidan,12.5,9.7,11.4,4.5,13,15
1,22423178,13,15.5,15,14.001,12.835,18.076923,16.1,"5,25",7.884615,12.23,14.25,11.4,Abbasli Ismayil,13.1,17.1,15.7,9,17,15.75
2,22423324,17,15,"17,75",18.667,12.1685,19.230769,15.5,"12,75",14.807692,17.67,11,12.6,Abbaszada Tunar,10.1,17.8,11.8,12.5,17,15
3,22422983,19,11.5,14,12.002,7.002,15.897436,16.2,"2,50",8.5,4.07,0.5,ab,Abdurahmanov Amir,0,5.4,11.6,NaN,10,13.25
4,22423198,15,13.5,16,12.335,7.8345,15.769231,12.3,"4,75",2.884615,2.22,5,3.84,Abishov Mahammad,8.9,4.7,0.4,6.5,13,8.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,22423199,18,18,17,14.668,12.6685,11.645833,14.8,"16,25",13.46,10.56,10.55,2.34,Taghiyeva Mahsati,11.3,16.8,13.1,7,19,18.5
57,22423337,"10,5",16,12.5,14.668,14.0015,11.270833,12.3,"8,75",12.31,10,12.25,1.2,Valiyev Zaur,13.7,17.7,13.6,6,18,14.5
58,22423230,16,20,19.5,16.334,10.002,8.75,14.3,"12,50",12.31,3.7,5.75,4.44,Yusibzada Narmin,16.1,10.2,12.4,0,15,11
59,22423304,"18,5",17,18,14.668,13.168,13.020833,12.8,"11,75",7.69,6.06,8.8,0,Yusubov Telman,10.7,17.2,12.3,0.5,20,14.75
60,22423244,"18,5",20,16.5,14.668,11.1685,10.729167,11.6,"7,00",10.77,8.15,4,4.92,Zahidova Nazrin,8.9,16.6,14.7,5,18,12.5

## Math Final

In [125]:
df_math = pd.read_excel("grades/L1 Math CC3 Grade sheet.xlsx", sheet_name="CS")

In [126]:
df_math

,Unnamed: 0,Academic Year 2025/2026,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Computer science L1,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Semester 1,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
65,27,22423199,NaN,NaN,14,NaN
66,28,22423337,NaN,NaN,9.25,NaN
67,29,22423230,NaN,NaN,10.75,NaN
68,30,22423304,NaN,NaN,8.5,NaN
69,31,22423244,NaN,NaN,6,NaN

In [127]:
df_math.drop([0, 1, 2, 3, 4, 5, 6],inplace=True)
df_math.drop(["Unnamed: 0", "Unnamed: 2", "Unnamed: 3", "Unnamed: 5"], axis=1, inplace=True)
df_math.rename(columns={'Academic Year 2025/2026' : 'ID', 'Unnamed: 4' : 'Math Final'}, inplace=True)

In [128]:
df_math

          ID Math Final
7   22423021          6
8   22423178        7.5
9   22423324      17.25
10  22422983        1.5
11  22423198       4.75
..       ...        ...
65  22423199         14
66  22423337       9.25
67  22423230      10.75
68  22423304        8.5
69  22423244          6

[63 rows x 2 columns]

In [129]:
df_math['ID'] = df_math['ID'].astype(str).str.strip()

In [130]:
df = pd.merge(df, df_math, on="ID")

## Cleaning

In [131]:
df

,ID,French Midterm 1,French Final,French Oral,CSPC midterm,CSPC Final,CSPC PW,DSA total,Math midterm,AOM midterm,...,Thermodynamics,Point Mechanics,Surname Name,FrontEnd Final,FrontEnd PW,FrontEnd Project,Fluid Mechanics,Math Participation,Chem Labs,Math Final
0,22423021,17,18.5,"17,5",18.667,10.8355,15.769231,12,"3,50",9.615385,...,8.75,4.32,Abbasli Fidan,12.5,9.7,11.4,4.5,13,15,6
1,22423178,13,15.5,15,14.001,12.835,18.076923,16.1,"5,25",7.884615,...,14.25,11.4,Abbasli Ismayil,13.1,17.1,15.7,9,17,15.75,7.5
2,22423324,17,15,"17,75",18.667,12.1685,19.230769,15.5,"12,75",14.807692,...,11,12.6,Abbaszada Tunar,10.1,17.8,11.8,12.5,17,15,17.25
3,22422983,19,11.5,14,12.002,7.002,15.897436,16.2,"2,50",8.5,...,0.5,ab,Abdurahmanov Amir,0,5.4,11.6,NaN,10,13.25,1.5
4,22423198,15,13.5,16,12.335,7.8345,15.769231,12.3,"4,75",2.884615,...,5,3.84,Abishov Mahammad,8.9,4.7,0.4,6.5,13,8.75,4.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,22423199,18,18,17,14.668,12.6685,11.645833,14.8,"16,25",13.46,...,10.55,2.34,Taghiyeva Mahsati,11.3,16.8,13.1,7,19,18.5,14
57,22423337,"10,5",16,12.5,14.668,14.0015,11.270833,12.3,"8,75",12.31,...,12.25,1.2,Valiyev Zaur,13.7,17.7,13.6,6,18,14.5,9.25
58,22423230,16,20,19.5,16.334,10.002,8.75,14.3,"12,50",12.31,...,5.75,4.44,Yusibzada Narmin,16.1,10.2,12.4,0,15,11,10.75
59,22423304,"18,5",17,18,14.668,13.168,13.020833,12.8,"11,75",7.69,...,8.8,0,Yusubov Telman,10.7,17.2,12.3,0.5,20,14.75,8.5
60,22423244,"18,5",20,16.5,14.668,11.1685,10.729167,11.6,"7,00",10.77,...,4,4.92,Zahidova Nazrin,8.9,16.6,14.7,5,18,12.5,6

In [132]:
df.replace("Abs", 0, inplace=True)
df.replace("abs", 0, inplace=True)
df.replace("ab", 0, inplace=True)
df.replace(np.nan, 0, inplace=True)
df.replace("na", 0, inplace=True)

df.replace('Total', 0, inplace=True)

/tmp/ipykernel_13964/493447694.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("Abs", 0, inplace=True)
/tmp/ipykernel_13964/493447694.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("ab", 0, inplace=True)

In [133]:
df.dtypes

ID                     object
French Midterm 1       object
French Final          float64
French Oral            object
CSPC midterm          float64
CSPC Final            float64
CSPC PW               float64
DSA total             float64
Math midterm           object
AOM midterm           float64
AOM final             float64
Thermodynamics        float64
Point Mechanics       float64
Surname Name           object
FrontEnd Final         object
FrontEnd PW            object
FrontEnd Project       object
Fluid Mechanics       float64
Math Participation    float64
Chem Labs             float64
Math Final             object
dtype: object

In [134]:
#df['Math midterm'] = df['Math midterm'].str.strip()
#df['French Midterm 1'] = df['French Midterm 1'].str.strip()

#df['Math midterm'] = df['Math midterm'].astype(float)
#df['French Midterm 1'] = df['French Midterm 1'].astype(float)
df['Thermodynamics'].astype(float)
df = df.apply(lambda col: col.astype(str).str.replace(",", ".", regex=False))
#df = df.astype(float)

# Предположим, твой DataFrame df, а столбец X не трогаем
cols_to_convert = [c for c in df.columns if (c != 'Surname Name') & (c != 'Email')]  # все кроме X
df[cols_to_convert] = df[cols_to_convert].astype(float)

In [135]:
# IF AOM GRADE WILL BE RENEWED
# df.loc[df['ID'] == 22423005, 'AOM midterm'] = 16.15

In [136]:
df.dtypes

ID                    float64
French Midterm 1      float64
French Final          float64
French Oral           float64
CSPC midterm          float64
CSPC Final            float64
CSPC PW               float64
DSA total             float64
Math midterm          float64
AOM midterm           float64
AOM final             float64
Thermodynamics        float64
Point Mechanics       float64
Surname Name           object
FrontEnd Final        float64
FrontEnd PW           float64
FrontEnd Project      float64
Fluid Mechanics       float64
Math Participation    float64
Chem Labs             float64
Math Final            float64
dtype: object

In [137]:
#cols = df.columns.tolist()
#cols.remove('Surname Name')
#new_order = [cols[0], 'Surname Name'] + cols[1:]
#df.columns = new_order

# Ave

In [138]:
df['Ave'] = (df['French Midterm 1'] * 0.5
           + df['French Final'] * 0.75
           + df['French Oral'] * 0.75
           + df['CSPC midterm']    * 0.37
           + df['CSPC Final'] * 0.73
           + df['CSPC PW'] * 0.73
           + df['DSA total']     * 3.67
           + df['Math midterm']    * 1.33
           + df['AOM midterm'] * 0.44
           + df['AOM final'] * 0.88
           + df['Thermodynamics'] * 1.6
           + df['Point Mechanics'] * 1.6
           + df['FrontEnd Final'] * 0.92
           + df['FrontEnd PW'] * 0.18
           + df['FrontEnd Project'] * 0.73
           + df['Fluid Mechanics'] * 0.8
           + df['Math Participation'] * 0.67
           + df['Chem Labs'] * 1.33
           + df['Math Final'] * 2
             )   / 20


# 0.2015

In [139]:
df

,ID,French Midterm 1,French Final,French Oral,CSPC midterm,CSPC Final,CSPC PW,DSA total,Math midterm,AOM midterm,...,Point Mechanics,Surname Name,FrontEnd Final,FrontEnd PW,FrontEnd Project,Fluid Mechanics,Math Participation,Chem Labs,Math Final,Ave
0,22423021.0,17.0,18.5,17.50,18.667,10.8355,15.769231,12.0,3.50,9.615385,...,4.32,Abbasli Fidan,12.5,9.7,11.4,4.5,13.0,15.00,6.00,10.286341
1,22423178.0,13.0,15.5,15.00,14.001,12.8350,18.076923,16.1,5.25,7.884615,...,11.40,Abbasli Ismayil,13.1,17.1,15.7,9.0,17.0,15.75,7.50,12.979535
2,22423324.0,17.0,15.0,17.75,18.667,12.1685,19.230769,15.5,12.75,14.807692,...,12.60,Abbaszada Tunar,10.1,17.8,11.8,12.5,17.0,15.00,17.25,14.675412
3,22422983.0,19.0,11.5,14.00,12.002,7.0020,15.897436,16.2,2.50,8.500000,...,0.00,Abdurahmanov Amir,0.0,5.4,11.6,0.0,10.0,13.25,1.50,7.872271
4,22423198.0,15.0,13.5,16.00,12.335,7.8345,15.769231,12.3,4.75,2.884615,...,3.84,Abishov Mahammad,8.9,4.7,0.4,6.5,13.0,8.75,4.75,8.230925
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,22423199.0,18.0,18.0,17.00,14.668,12.6685,11.645833,14.8,16.25,13.460000,...,2.34,Taghiyeva Mahsati,11.3,16.8,13.1,7.0,19.0,18.50,14.00,13.205616
57,22423337.0,10.5,16.0,12.50,14.668,14.0015,11.270833,12.3,8.75,12.310000,...,1.20,Valiyev Zaur,13.7,17.7,13.6,6.0,18.0,14.50,9.25,11.168943
58,22423230.0,16.0,20.0,19.50,16.334,10.0020,8.750000,14.3,12.50,12.310000,...,4.44,Yusibzada Narmin,16.1,10.2,12.4,0.0,15.0,11.00,10.75,11.165997
59,22423304.0,18.5,17.0,18.00,14.668,13.1680,13.020833,12.8,11.75,7.690000,...,0.00,Yusubov Telman,10.7,17.2,12.3,0.5,20.0,14.75,8.50,10.889070
60,22423244.0,18.5,20.0,16.50,14.668,11.1685,10.729167,11.6,7.00,10.770000,...,4.92,Zahidova Nazrin,8.9,16.6,14.7,5.0,18.0,12.50,6.00,10.134713

In [140]:
df.sort_values(by="Ave", ascending=False, inplace=True)

In [141]:
df["Rank"] = [i for i in range(len(df))]
df["Rank"] += 1

In [142]:
df = pd.merge(df_names, df, on="ID")
df.sort_values(by="Ave", ascending=False, inplace=True)
df.set_index('Rank', inplace=True)
df

,ID,Email,French Midterm 1,French Final,French Oral,CSPC midterm,CSPC Final,CSPC PW,DSA total,Math midterm,...,Point Mechanics,Surname Name,FrontEnd Final,FrontEnd PW,FrontEnd Project,Fluid Mechanics,Math Participation,Chem Labs,Math Final,Ave
Rank,,,,,,,,,,,,,,,,,,,,,
1,22423196,m.javadzade@ufaz.az,19.0,20.0,19.75,19.000,18.0005,17.777778,16.6,20.00,...,19.60,Javadzade Mahammad,16.7,17.0,16.1,20.0,20.0,12.750,19.25,18.185177
2,22423005,f.budagov@ufaz.az,19.0,18.0,19.00,18.667,15.3345,17.777778,17.7,15.00,...,18.00,Budagov Farhad,16.1,15.6,16.6,20.0,20.0,17.250,18.50,17.253516
3,22422989,a.jafarova1@ufaz.az,19.5,19.0,19.50,17.334,12.0020,14.074074,17.7,18.75,...,17.34,Jafarova Aziza,14.3,17.5,13.5,12.0,19.0,17.250,19.00,17.178766
4,22423162,h.aliyev@ufaz.az,19.0,18.5,17.00,18.667,16.0010,18.461538,17.3,18.25,...,17.20,Aliyev Hakim,13.1,17.8,17.3,13.5,18.0,15.000,17.50,16.890576
5,22423200,m.akhundova@ufaz.az,19.0,20.0,19.00,14.668,15.3340,19.743590,18.3,17.50,...,14.52,Akhundova Maryam,16.1,16.1,16.9,17.0,20.0,18.125,15.25,16.820474
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,22322638,y.rashidli@ufaz.az,10.5,12.5,6.00,18.667,6.0035,9.312500,12.8,0.75,...,0.24,Rashıḋlı ̇Yusif,8.9,14.3,9.1,4.0,18.0,8.750,3.50,8.186543
58,22422983,a.abdurahmanov@ufaz.az,19.0,11.5,14.00,12.002,7.0020,15.897436,16.2,2.50,...,0.00,Abdurahmanov Amir,0.0,5.4,11.6,0.0,10.0,13.250,1.50,7.872271
59,22422997,e.aliyev2@ufaz.az,13.5,12.0,12.75,13.335,9.6680,17.051282,11.7,0.75,...,8.70,Aliyev Elnur,0.0,11.3,0.0,6.5,6.0,11.500,0.75,7.302221
60,22322607,m.gasimov1@ufaz.az,13.0,16.0,0.00,12.335,5.8360,12.000000,10.7,3.75,...,2.40,Gasimov Murad,8.2,14.6,13.1,4.0,4.0,10.250,4.00,6.785042
61,22322620,r.alipashayev@ufaz.az,14.0,10.5,10.00,0.000,0.0000,0.000000,0.0,0.00,...,6.96,Alı̇pashayev Ravan,0.0,0.0,0.0,4.0,16.0,0.000,0.25,2.660245

In [143]:
df

,ID,Email,French Midterm 1,French Final,French Oral,CSPC midterm,CSPC Final,CSPC PW,DSA total,Math midterm,...,Point Mechanics,Surname Name,FrontEnd Final,FrontEnd PW,FrontEnd Project,Fluid Mechanics,Math Participation,Chem Labs,Math Final,Ave
Rank,,,,,,,,,,,,,,,,,,,,,
1,22423196,m.javadzade@ufaz.az,19.0,20.0,19.75,19.000,18.0005,17.777778,16.6,20.00,...,19.60,Javadzade Mahammad,16.7,17.0,16.1,20.0,20.0,12.750,19.25,18.185177
2,22423005,f.budagov@ufaz.az,19.0,18.0,19.00,18.667,15.3345,17.777778,17.7,15.00,...,18.00,Budagov Farhad,16.1,15.6,16.6,20.0,20.0,17.250,18.50,17.253516
3,22422989,a.jafarova1@ufaz.az,19.5,19.0,19.50,17.334,12.0020,14.074074,17.7,18.75,...,17.34,Jafarova Aziza,14.3,17.5,13.5,12.0,19.0,17.250,19.00,17.178766
4,22423162,h.aliyev@ufaz.az,19.0,18.5,17.00,18.667,16.0010,18.461538,17.3,18.25,...,17.20,Aliyev Hakim,13.1,17.8,17.3,13.5,18.0,15.000,17.50,16.890576
5,22423200,m.akhundova@ufaz.az,19.0,20.0,19.00,14.668,15.3340,19.743590,18.3,17.50,...,14.52,Akhundova Maryam,16.1,16.1,16.9,17.0,20.0,18.125,15.25,16.820474
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,22322638,y.rashidli@ufaz.az,10.5,12.5,6.00,18.667,6.0035,9.312500,12.8,0.75,...,0.24,Rashıḋlı ̇Yusif,8.9,14.3,9.1,4.0,18.0,8.750,3.50,8.186543
58,22422983,a.abdurahmanov@ufaz.az,19.0,11.5,14.00,12.002,7.0020,15.897436,16.2,2.50,...,0.00,Abdurahmanov Amir,0.0,5.4,11.6,0.0,10.0,13.250,1.50,7.872271
59,22422997,e.aliyev2@ufaz.az,13.5,12.0,12.75,13.335,9.6680,17.051282,11.7,0.75,...,8.70,Aliyev Elnur,0.0,11.3,0.0,6.5,6.0,11.500,0.75,7.302221
60,22322607,m.gasimov1@ufaz.az,13.0,16.0,0.00,12.335,5.8360,12.000000,10.7,3.75,...,2.40,Gasimov Murad,8.2,14.6,13.1,4.0,4.0,10.250,4.00,6.785042
61,22322620,r.alipashayev@ufaz.az,14.0,10.5,10.00,0.000,0.0000,0.000000,0.0,0.00,...,6.96,Alı̇pashayev Ravan,0.0,0.0,0.0,4.0,16.0,0.000,0.25,2.660245

In [144]:
df[df["Email"] == "m.akhundova@ufaz.az"]

,ID,Email,French Midterm 1,French Final,French Oral,CSPC midterm,CSPC Final,CSPC PW,DSA total,Math midterm,...,Point Mechanics,Surname Name,FrontEnd Final,FrontEnd PW,FrontEnd Project,Fluid Mechanics,Math Participation,Chem Labs,Math Final,Ave
Rank,,,,,,,,,,,,,,,,,,,,,
5,22423200,m.akhundova@ufaz.az,19.0,20.0,19.0,14.668,15.334,19.74359,18.3,17.5,...,14.52,Akhundova Maryam,16.1,16.1,16.9,17.0,20.0,18.125,15.25,16.820474

In [145]:
df[df['Email'] == 'f.budagov@ufaz.az']

,ID,Email,French Midterm 1,French Final,French Oral,CSPC midterm,CSPC Final,CSPC PW,DSA total,Math midterm,...,Point Mechanics,Surname Name,FrontEnd Final,FrontEnd PW,FrontEnd Project,Fluid Mechanics,Math Participation,Chem Labs,Math Final,Ave
Rank,,,,,,,,,,,,,,,,,,,,,
2,22423005,f.budagov@ufaz.az,19.0,18.0,19.0,18.667,15.3345,17.777778,17.7,15.0,...,18.0,Budagov Farhad,16.1,15.6,16.6,20.0,20.0,17.25,18.5,17.253516

In [146]:
df.count()

ID                    61
Email                 61
French Midterm 1      61
French Final          61
French Oral           61
CSPC midterm          61
CSPC Final            61
CSPC PW               61
DSA total             61
Math midterm          61
AOM midterm           61
AOM final             61
Thermodynamics        61
Point Mechanics       61
Surname Name          61
FrontEnd Final        61
FrontEnd PW           61
FrontEnd Project      61
Fluid Mechanics       61
Math Participation    61
Chem Labs             61
Math Final            61
Ave                   61
dtype: int64

# Utilites

In [147]:
def calculate_average(series):
    french_mid, french_final, french_oral, cspc_mid, cspc_final, cspc_pw, dsa, math_mid, aom_mid, aom_final, thermoexam, pointmech, frontend_final, frontendPW, frontendProject, fluid, math_particip, labs, mathf = series
    return (
        0.5 * french_mid +
        0.75 * french_final +
        0.75 * french_oral +
        0.37 * cspc_mid +
        0.73 * cspc_final +
        0.73 * cspc_pw +
        3.67 * dsa +
        1.33 * math_mid +
        0.44 * aom_mid +
        0.88 * aom_final +
        1.6 * thermoexam +
        1.6 * pointmech +
        0.92 * frontend_final +
        0.18 * frontendPW +
        0.73 * frontendProject +
        0.8 * fluid +
        0.67 * math_particip +
        1.33 * labs +
        2 * mathf
    ) / (0.5 + 0.75 + 0.75 + 0.37 + 0.73 + 0.73 + 3.67 + 1.33 + 0.44 + 0.88 + 1.6 + 1.6 + 0.92 + 0.18 + 0.73 + 0.8 + 0.67 + 1.33 + 2)

In [148]:
(0.5 + 0.75 + 0.75 + 0.37 + 0.73 + 0.73 + 3.67 + 1.33 + 0.44 + 0.88 + 1.6 + 1.6 + 0.92 + 0.18 + 0.73 + 0.8 + 0.67 + 1.33 + 2)

19.980000000000004

In [149]:
def calculate_average_by_email(email):
    row = df[df['Email'] == email].iloc[0, 3:22]
    row = row.astype(float)
    return calculate_average(row)

In [150]:
def calculate_average_by_name(name, df):
    email = revealStudentsEmail(name, df)
    if email == None:
        return None
    return calculate_average_by_email(email)

In [151]:
    def revealStudent(namesurname, df):
        name, surname = namesurname.split(' ')
        email = name[0].casefold() + '.' + surname.casefold()

        data = df[df['Email'] == (email+'@ufaz.az')]

        # if there is no such email
        if data.empty:
            data = df[df['Email'] == (email+ '1' + '@ufaz.az')]
            if data.empty:
                data = df[df['Email'] == (email+ '2' + '@ufaz.az')]
                if data.empty:
                    data = df[df['Email'] == (email+ '3' + '@ufaz.az')]
                    if data.empty:
                        print('Seems that there is no such a student.')
                        return None

        return data

In [152]:
def revealStudentsEmail(namesurname, df):
    name, surname = namesurname.split(' ')
    email_carcass = name[0].casefold() + '.' + surname.casefold()

    data = df[df['Email'] == (email_carcass+'@ufaz.az')]
    email = email_carcass+'@ufaz.az'
    if data.empty:
        data = df[df['Email'] == (email_carcass+ '1' + '@ufaz.az')]
        email = email_carcass+ '1' + '@ufaz.az'
        if data.empty:
            data = df[df['Email'] == (email_carcass+ '2' + '@ufaz.az')]
            email = email_carcass+ '2' + '@ufaz.az'
            if data.empty:
                data = df[df['Email'] == (email_carcass+ '3' + '@ufaz.az')]
                email = email_carcass+ '3' + '@ufaz.az'
                if data.empty:
                    print('Seems that there is no such a student.')
                    return None
    return email

In [153]:
df = df[['ID', 'Surname Name', 'Email', 'French Midterm 1', 'French Final', 'French Oral', 'CSPC midterm', 'CSPC Final', 'CSPC PW', 'DSA total', 'Math midterm', 'AOM midterm', 'AOM final', 'Thermodynamics', 'Point Mechanics', 'FrontEnd Final', 'FrontEnd PW', 'FrontEnd Project', 'Fluid Mechanics', 'Math Participation', 'Chem Labs', 'Math Final', 'Ave']]

In [154]:
df

,ID,Surname Name,Email,French Midterm 1,French Final,French Oral,CSPC midterm,CSPC Final,CSPC PW,DSA total,...,Thermodynamics,Point Mechanics,FrontEnd Final,FrontEnd PW,FrontEnd Project,Fluid Mechanics,Math Participation,Chem Labs,Math Final,Ave
Rank,,,,,,,,,,,,,,,,,,,,,
1,22423196,Javadzade Mahammad,m.javadzade@ufaz.az,19.0,20.0,19.75,19.000,18.0005,17.777778,16.6,...,20.00,19.60,16.7,17.0,16.1,20.0,20.0,12.750,19.25,18.185177
2,22423005,Budagov Farhad,f.budagov@ufaz.az,19.0,18.0,19.00,18.667,15.3345,17.777778,17.7,...,16.00,18.00,16.1,15.6,16.6,20.0,20.0,17.250,18.50,17.253516
3,22422989,Jafarova Aziza,a.jafarova1@ufaz.az,19.5,19.0,19.50,17.334,12.0020,14.074074,17.7,...,18.50,17.34,14.3,17.5,13.5,12.0,19.0,17.250,19.00,17.178766
4,22423162,Aliyev Hakim,h.aliyev@ufaz.az,19.0,18.5,17.00,18.667,16.0010,18.461538,17.3,...,17.00,17.20,13.1,17.8,17.3,13.5,18.0,15.000,17.50,16.890576
5,22423200,Akhundova Maryam,m.akhundova@ufaz.az,19.0,20.0,19.00,14.668,15.3340,19.743590,18.3,...,11.25,14.52,16.1,16.1,16.9,17.0,20.0,18.125,15.25,16.820474
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,22322638,Rashıḋlı ̇Yusif,y.rashidli@ufaz.az,10.5,12.5,6.00,18.667,6.0035,9.312500,12.8,...,7.75,0.24,8.9,14.3,9.1,4.0,18.0,8.750,3.50,8.186543
58,22422983,Abdurahmanov Amir,a.abdurahmanov@ufaz.az,19.0,11.5,14.00,12.002,7.0020,15.897436,16.2,...,0.50,0.00,0.0,5.4,11.6,0.0,10.0,13.250,1.50,7.872271
59,22422997,Aliyev Elnur,e.aliyev2@ufaz.az,13.5,12.0,12.75,13.335,9.6680,17.051282,11.7,...,0.00,8.70,0.0,11.3,0.0,6.5,6.0,11.500,0.75,7.302221
60,22322607,Gasimov Murad,m.gasimov1@ufaz.az,13.0,16.0,0.00,12.335,5.8360,12.000000,10.7,...,0.50,2.40,8.2,14.6,13.1,4.0,4.0,10.250,4.00,6.785042
61,22322620,Alı̇pashayev Ravan,r.alipashayev@ufaz.az,14.0,10.5,10.00,0.000,0.0000,0.000000,0.0,...,0.00,6.96,0.0,0.0,0.0,4.0,16.0,0.000,0.25,2.660245

In [168]:
df[df['Ave'] > 17]

,ID,Surname Name,Email,French Midterm 1,French Final,French Oral,CSPC midterm,CSPC Final,CSPC PW,DSA total,...,Thermodynamics,Point Mechanics,FrontEnd Final,FrontEnd PW,FrontEnd Project,Fluid Mechanics,Math Participation,Chem Labs,Math Final,Ave
Rank,,,,,,,,,,,,,,,,,,,,,
1,22423196,Javadzade Mahammad,m.javadzade@ufaz.az,19.0,20.0,19.75,19.000,18.0005,17.777778,16.6,...,20.0,19.60,16.7,17.0,16.1,20.0,20.0,12.75,19.25,18.185177
2,22423005,Budagov Farhad,f.budagov@ufaz.az,19.0,18.0,19.00,18.667,15.3345,17.777778,17.7,...,16.0,18.00,16.1,15.6,16.6,20.0,20.0,17.25,18.50,17.253516
3,22422989,Jafarova Aziza,a.jafarova1@ufaz.az,19.5,19.0,19.50,17.334,12.0020,14.074074,17.7,...,18.5,17.34,14.3,17.5,13.5,12.0,19.0,17.25,19.00,17.178766

In [159]:
df.to_excel("grades/STATS.xlsx")

In [156]:
print(calculate_average_by_name('H Aliyev', df))
print(calculate_average_by_name('M Javadzade', df))
print(calculate_average_by_name('F Budagov', df))
print(calculate_average_by_name('Aziza Jafarova', df))
print(calculate_average_by_name('Maryam Akhundova', df))
print(calculate_average_by_name('Mika Guliyev', df))

16.907483098426887
18.203380519489485
17.270786502395467
17.195961665220217
16.83731137534688
16.02771229901786

In [157]:
print(calculate_average_by_name('F Burjaliyev', df))

9.341820942859394

In [158]:
for each in df['Surname Name']:
    if each == 'Mohammad Bakir Isa':
        continue

    surname, name = each.split(' ')
    each = name + ' ' + surname
    print(each, end='\t')
    print(calculate_average_by_name(each, df))

Mahammad Javadzade	18.203380519489485
Farhad Budagov	17.270786502395467
Aziza Jafarova	17.195961665220217
Hakim Aliyev	16.907483098426887
Maryam Akhundova	16.83731137534688
Murad Atlukhanov	16.66033248627627
Nasrin Asadli	16.321501353786864
Rasul Rahimov	16.272868618618617
Mikayil Guliyev	16.02771229901786
Nadir Azizov	15.98092691396242
Eldar Mutallimov	15.815701951951946
Kamil Hasanli	15.220207886043346
Tamara Hasanova	15.139636917395471
Narmina Rzayeva	14.925791291291288
Narmina Sharifova	14.819441524979972
Huseyn Balayev	14.72590815159159
Ilaha Algayeva	14.70049452668091
Tunar Abbaszada	14.69010215982405
Nilufar Ilyasli	14.303180532492489
Bahruz Hajiyev	14.027061140967117
Ayhan Safarov	13.989518351806806
Said Aghamaliyev	13.944549568940092
Parvin Salahov	13.598863697152153
Igbal Rahimli	13.339020520520517
Mahsati Taghiyeva	13.218835001546541
Ismayil Abbasli	12.992527758640176
Sabuhi Garibov	12.63440158445715
Tunar Khankishizade	12.521417407972967
Ali Majidzade	12.507571274829827
Kamran Huseynli	12.416119610175173
Javid Bayramli	12.374805876239314
Gunay Akhundova	12.163821327831675
Tofig Alizada	12.153065642537538
Narmin Seyidli	11.908880213668665
Teymur Alasgarov	11.60400698761646
Tural Haji-Nabili	11.250417045128588
Famil Gulmammadov	11.23096289722145
Yusif Khalafli	11.213173006461458
Zaur Valiyev	11.180123289834833
Narmin Yusibzada	11.177174174174173
Jansu Najafzade	11.133871705160157
Telman Yusubov	10.899970386931932
Fidan Mammadli	10.74197467823323
Fidan Abbasli	10.296637271915376
Riad Rahimbayov	10.275816649995493
Nazrin Zahidova	10.144857691146141
Fatma Mammadova	9.717615699154155
Gulzar Mammadli	9.57876092747247
Sami Salahov	9.466408158158155
Farhad Burjaliyev	9.341820942859394
Raul Ahmadzada	9.194520873559327
Nuray Rzali	8.990413079624624
Daniil Kuchinskiy	8.37989527480981
Elsel Mammadov	8.378444360905902
Mahammad Abishov	8.239164375942478
̇Yusif Rashıḋlı	Seems that there is no such a student.
None
Amir Abdurahmanov	7.88015156191191
Elnur Aliyev	7.30953005564988
Murad Gasimov	6.791834103334102
Ravan Alı̇pashayev	Seems that there is no such a student.
None